(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1920,
	height: 1200,
	fps: 24,
	color: "#999999",
	manifest: []
};



// symbols:



(lib.Símbolo6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("Egp0AsKQjngkiniiQikiggujeQhWBHhqAeQhvAghygSQjVgih+ivQh/iuAijWQAViCBPhoQBMhlBzg2QhHhhgeh0Qgdh5AUh8QAoj6DNiVQDOiUD6AnQBvARBiA5QgYhkAQhrQAijVCuh8QCwh+DVAhQDVAjB+CtQB/CugiDVQgFAcgIAeQCHh+Cvg3QC1g5C9AeQFKA1DFEPQDEEPg0FLQg1FLkPDFQkQDElKg2QiQgWiAhIQArBhAOBoQAQBtgSBsQgxEwj4C1QjECNjlAAQg/AAhBgLgEApYAVXQh0g0gth2Qgth3AzhzQAWgyAogoQgoAGgogFQgpgFgmgRQhqgvgqhtQgphtAvhqQAlhRBLgtQBKgsBWAFQgSgmAAgqQgBgsASgoIAAgCQgviUBBiPQA1h3BwhCQBthCB+AHQgag4gBg+QgBg/Aag7QAxhuBxgrQBwgrBuAyQBDAdAsA6QArA4ANBFQA+gYBDAAQBFACBAAdQCBA5AzCEQAyCEg6CBQgZA5gtAtQA6AAA3AXQBuAxAqBwQArBxgxBuQgxBthwArQhxArhtgxIgdgPQAwBbAEBmQAFBpgsBhQhMCriuBCQiuBDiqhMQgZgMgXgNQgGAngRAlQgzB0h3AtQg3AVg3AAQg+AAg9gbgEAq3ghlQhGgggchHQgchIAghHQAfhGBIgbQAfgNAiAAQgUgOgPgTQgPgUgJgYQgZhCAchAQAdhBBCgZQAzgTA0ANQAzANAjAnQAJgZARgSQATgTAYgJQAvgSAtAUQAtAVASAuQALAcgEAeQgDAdgRAYQAZALATAUQAUAUALAbQAVA3gZA1QgXA1g3AVQgYAKgaAAQAQARAKAXQARAugUAuQgUAtgvARQguASgtgUQgugVgSgtIgDgOQgNApgdAfQgdAhgpAPQgiANghAAQgmAAglgRg");
	this.shape.setTransform(414.2,259.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-24,828.4,567.4);


(lib.Símbolo5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("A5ib1QhhgKhUguQhSgug7hJQg/BLhbAmQheAmhlgLQiogRhpiCQhqiDARimQAKhZAthNQAthJBGgyQidhQhXiaQhYifATi1QAYjtC6iXQC5iUDtAZQBWAIBOAhQBLAfBBAzQgdhtAMhwQAbkDDKikQDKikECAaQEDAcCkDJQCkDLgbECQgPCShPB8QhMB5h6BLQAYABAWACQCmARBqCCQBqCCgSCnQgRCniCBqQiCBpingRQhTgJhGgnQAXBVgKBXQgUDEiZB8QiEBrijAAQgbAAgbgDgAaBCsQhxhtgDibIAAgDQg2ADg5gPQiZgmhRiHQguhNgHhYQgHhWAghRIgXAPQhXA1higZQhjgYg0hXQg0hWAYhjQAZhiBWg1QAsgZAwgHQgqghgbgtQg9hmAch0QAdh0Bmg9QAzgeA5gIQA4gIA3AOQADg8AfgyQAfg1A1ggQBXg0BiAYQBjAZA0BXQAbAuAGA2QAGAzgQAyQBpgTBiAsQBkAsA5BeQAQAbALAcIAUAHQA0AWApAnQAhgyA0gdQA1geA9gBQBmgBBJBGQBJBGABBmQABA1gWAyQgVAvgmAjQBkAkA/BXQBBBZABBuQADCQhkBnQhkBoiQADQg0ABgxgOQgwgOgqgaQAZBAABBEQADCbhtByQhtBwieAEIgHAAQiYAAhvhrg");
	this.shape.setTransform(281.5,178.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,563,357);


(lib.Símbolo4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("EhbiCoIQvNjTolthQjFk0hjliQhilTgCllQkZGPmKEJQuIJqwmjkQwljmpWurQjklohtl/Qojh/k4nYQlBnpB2o8QB2o+HolAQC3h4DMg7Qj9idixkMQjoljgDmOQhDhNg6hYQlBnpB2o8QBTmVEMkWQnViSkXmnQlBnpB2o8QB2o8HolAQEXi3FJgoQE+glExBoQgjgrgagoQjPk7BLlxQBNlwE7jQQE7jPFxBLQFwBNDQE7QBmCdAgCxQBzihClhqQFyjzGyBZQCFAbByA2QgggrgXgzQhPixBFi1QBFi1CxhPQBlgtBuAFQBqAEBeAzQgJgQgGgPQgzhyAsh1QAsh0BzgzQBxgzB1AsQB1AtAzByQAZA5ABA8QAugvA8gaQCGg8CJA0QCJA1A8CGQAdBCACBIQAAA/gVA8IAPAPQAoAKAjAUQCflSE/jLQFYjaGYATQGmASE6D6QAeiDBshYQCChpCnARQBTAJBGAnQgXhVAKhXQAVjECYh8QCah9DEAVQBdAJBSAsQAGgkAIgjQBZlvFCjEQCrhoDHgWQDAgWC5A6Qg/lXBzlEQhNAwhiAKQinAOiBhrQhAg2glhHQgcBTg4BCQh/CXjEASQjFASiXh/QhKg+gshWQgrhTgHheQhgAbhggUQhigUhPhCQiBhsgPimQgPioBsiAQA5hFBRgmQBNgkBXgCQhWiaAPixQAPi0B1iMQCZi3DugWQCQgNB8A0QAChpAahsQBZluFBjEQCshpDHgWQDAgWC5A7QhImGCfltQCjl1FdjVQHKkXIJB9QFvBZD3D+QApgfAtgbQCshpDHgWQC+gWC5A7QhImGCfltQCjl1FdjVQHKkXIJB9QIJB/EYHLQBkCjAvC6QAuCygFC5QCfjKDZiDQHTkdIPBlIARgpQCkl1FdjVQHJkXIKB9QIIB/EYHLQBlCjAvC6QAUBMAKBNQDmh2Dwg1QHOj2IKB+QI4CLEwHyQApBDAhBFQDMDiCfEqQCsE/BQFqQBPFbgJFqQEPmLFyj/QNSpTPKEMQPIEOIIPNQIGPPjqRTQjsRWtSJRQnmFTozA3QogAzoDjeQA5BVArBQQFOJ0iWLLQgTBbgaBWQJGQjkMSvQkSTDvbKLQo1F1qNA8Qp5A5pWj1QBDBeAxBYQGEKxiuMSQhQFjiuEZQCPEugQFnQgcJImuGLQmxGKpHgbQlOgPkhihQkEiSi0jvIgYACQABAigCAgQgRF4kWD/QkWD+l4gRIgzgDIgBAZQgcJImuGKQmxGKpHgaQlOgPkhihQkXidi7kHQADA3gCAwQgQFhj2D2QhzEBjgDOQmxGKpHgaQlMgPkhihQkXidi7kHQADA3gCAwQgRF4kWD/QkWD9l4gQQl5gRj/kWQhZhjg4hvQkwCSlrgQQiAgGh6gcQjLDqkKC2QpfGeqsAAQj8AAkGg4gEi12AUBIgRgWIgLAMIAcAKIAAAAgEA2shxPIANgZIgrgQIAeApg");
	this.shape.setTransform(1410.8,1081.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,2821.7,2163.3);


(lib.Símbolo3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("EgdOCoZQoJh/kYnLQhkijgvi6QguiyAFi5QifDKjZCDQnTEdoPhlIgRApQikF1ldDVQnJEXoKh9QoIh/kYnLQhlijgvi6QgUhMgKhNQjmB2jwA1QnOD2oKh+Qo4iLkwnyQgphDghhFQjMjiifkqQisk/hQlqQhPlbAJlqQkPGLlyD/QtSJTvKkMQvIkOoIvNQoGvPDqxTQDsxWNSpRQHmlTIzg3QIggzIDDeQg5hVgrhQQlOp0CWrLQAThbAahWQpGwjEMyvQESzDPbqLQI1l1KNg8QJ5g5JWD1QhDhegxhYQmEqxCusSQBQljCukZQiPkuAQlnQAcpIGumLQGxmKJHAbQFOAPEhChQEECSC0DvIAYgCQgBgiACggQARl4EWj/QEWj+F4ARIAzADIABgZQAcpIGumKQGxmKJHAaQFOAPEhChQEXCdC7EHQgDg3ACgwQAQlhD2j2QBzkBDgjOQGxmKJHAaQFMAPEhChQEXCdC7EHQgDg3ACgwQARl4EWj/QEWj9F4AQQF5ARD/EWQBZBjA4BvQEwiSFrAQQCAAGB6AcQDLjqEKi2QM/o3PODRQPNDTIlNhQDFE0BjFiQBiFTACFlQEZmPGKkJQOIpqQmDkQQlDmJWOrQDkFoBtF/QIjB/E4HYQFBHph2I8Qh2I+noFAQi3B4jMA7QD9CdCxEMQDoFjADGOQBDBNA6BYQFBHph2I8QhTGVkMEWQHVCSEXGnQFBHph2I8Qh2I8noFAQkXC3lJAoQk+AlkxhoQAjArAaAoQDPE7hLFxQhNFwk7DQQk7DPlxhLQlwhNjQk7QhmidggixQhzChilBqQlyDzmyhZQj6g0i7iRQgSF5kVD9QkXD+l4gRQjJgJixhcQishah4iYQifFslQDWQkEClkpAdIAHAJQBpCCgRCnQgRCniCBqQiCBpingRQhTgJhGgnQAXBVgKBXQgVDEiYB8QiaB9jEgVQhggKhVguQgxgbgpgmQAMAYAKAZQA5CehGCYQgmBRhEA5QhCA4hTAYQB7B+AgCvQAfCyhNClQhjDZjgBTQjhBRjZhlQhNgjg/g5Qg9g3gshGQgJBzgwBmQhuDsj0BaQifA6ibgaQBXAdBSAwQDEB0B4DDQDEFDhZFuQhZFulBDEQisBpjHAWQjAAWi5g7QBIGGifFtQijF1ldDVQnKEXoJh9QlvhZj3j+QgpAfgtAbQisBpjHAWQi+AWi5g7QBIGGifFtQijF1ldDVQk8DBlaAAQicAAihgngEg2NBx5IgegpIgNAZIArAQIAAAAgEAxyBhPQgbgKgbgNQgjgQgggTIgJAqQBCADBAANIAAAAgEAv4BPpQBYg2BngYIgqgRQhGgggxgyQgJBZgVBYgEA7JAtQIAbAPQDEBzB3DEQDFFDhZFtIgEAOQBAALA/AdQAeAOAbARQAOhCAjg7QAshJBGgyQidhQhXiaQhXifATi1QATi8B4iGQj0hIimi8QhUCqh+CHgEBRRArhIgIgiIgVAMIAdAWIAAAAgEC2IgTqIALgMIgcgKIARAWg");
	this.shape.setTransform(1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,2821.7,2163.3);


(lib.scene01_drag_slider_grafico = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").p("AMWAAQAAA6gMASQgZAohlAaQizAunZAAQnYAAizguQhlgagZgoQgMgSAAg6QAAg6AMgSQAZgnBlgaQCzguHYAAQHZAACzAuQBlAaAZAnQAMASAAA6g");
	this.shape.setTransform(79.1,18.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.2).p("AHvAAQAAASgIAFQgQAMg/AIQhwAOkoAAQknAAhwgOQg/gIgQgMQgIgFAAgSQAAgQAIgGQAQgMA/gIQBwgOEnAAQEoAABwAOQA/AIAQAMQAIAGAAAQg");
	this.shape_1.setTransform(78.9,18.7,1,1.448);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B72B5").s().p("AmWArQhAgIgQgMQgIgFAAgSQAAgQAIgGQAQgMBAgIQBvgOEnAAQEoAABwAOQA/AIAQAMQAHAGAAAQQAAASgHAFQgQAMg/AIQhwAOkoAAQknAAhvgOg");
	this.shape_2.setTransform(78.9,18.7,1,1.448);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.9,-1,161.9,39.7);


(lib.linea_textos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EBahAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA1AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEBYpAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBWxAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBU5AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEBTBAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBRJAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBPRAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEBNZAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBLhAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBJpAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEBHxAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBF5AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBEBAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEBCJAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEBARAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEA+ZAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEA8hAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEA6pAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEA4xAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEA25AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEA1BAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAzJAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEAxRAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAvZAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAthAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEArpAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEApxAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAn5AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEAmBAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAkJAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEAiRAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEAgZAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAehAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAcpAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAaxAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAY5APQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAXBAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAVJAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgATRAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgARZAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAPhAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgANpAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgALxAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAJ5APQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAIBAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAGJAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAERAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgACZAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAAhAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAhVAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAjNAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAlFAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAm9APQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAo1APQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAqtAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAslAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAudAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgAwVAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgAyNAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgA0FAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgA19APQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgA31APQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgA5tAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgA7lAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgA9dAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgA/VAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEghNAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEgjFAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgk9AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgm1AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEgotAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgqlAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgsdAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEguVAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgwNAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEgyFAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEgz9AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEg11AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEg3tAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEg5lAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEg7dAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEg9VAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEg/NAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhBFAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhC9AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhE1AAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhGtAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhIlAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhKdAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhMVAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhONAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhQFAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhR9AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhT1AAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhVtAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhXlAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABgEhZdAAPQgGgBgEgEQgFgEAAgGQAAgFAFgEQAEgEAGgBIA8AAQAGABAFAEQAEAEAAAFQAAAGgEAEQgFAEgGABgEhbVAAPQgGgBgFgEQgEgEAAgGQAAgFAEgEQAFgEAGgBIA8AAQAGABAEAEQAFAEAAAFQAAAGgFAEQgEAEgGABg");
	this.shape.setTransform(584.7,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,1172.3,3);


(lib.Interpolación6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#091832").s().p("AKNDVQgbgbAAgoQAAgwAqghQApghBBAAQASAAAWAIQAAhLhEAAQg0ABgcAcIgYgvQAQgMAcgKQAcgJAZAAQBFAAAfAfQAeAfAABCIAABwQAAApAZAOIAAAcQgiAAgRgJQgRgKgHgXQghAqhFABQglAAgbgbgALEBfQgbAWAAAdQAAAyA6AAQAqgBAhgoIAAhMQgbgFgKgBQgqABgbAVgAFuDEQgqgrAAhKQAAhLAsgqQArguBMAAQAYAAAdAKQAcALAOAKIgcAnQgJgIgVgHQgWgJgUABQguAAgaAfQgbAfAAA2QAAA4AbAdQAbAdAxAAQAlgBAmgdIAWAwQgtAdhCAAQhAgBgqgrgAhYDXIAUg1QAvAfAaAAQAzgBAAgrQAAgfgxgWQglgSgNgJQgNgJgKgLQgKgMgFgNQgFgNAAgNQAAgnAcgWQAdgVArAAQAiAAA0AVIgPA0QghgbgiABQgSAAgNAJQgOAKAAAOQAAAcAgAQIAoASQAlARAQAVQARAVAAAhQAAApgeAYQgdAZg1AAQgvgBgsgYgAlzDSQgbgeAAg3IAAjMIA4AAIAADHQAABIA/ABQAbAAAXgQQAXgQAHgVIAAjbIA4AAIAAE4Ig4AAIAAgrQgJASgcAQQgdAQgbAAQgzgBgcgdgADJDpIAAkJIgrAAIAAgvIBiAAIAAE4gAoSDpIAAjGQAAhJhAABQgUgBgSANQgRAMgHAOIAADoIg4AAIAAjfQAAgUgRgOQgRgNgdAAQgRgBgTANQgTAOgIANIAADnIg3AAIAAk4IAkAAIATAlQAggqAwAAQBEAAAaAqQAKgSAZgMQAagMAbAAQAwAAAbAdQAbAcAAAzIAADRgADPiKQgKgLAAgNQAAgPAKgKQAKgKAOAAQAPAAAKAKQAKALAAAOQAAANgKALQgKAKgPAAQgOAAgKgKgAlFiNIAxhiIA6AAIhCBig");
	this.shape.setTransform(90.9,-3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AIjDFQgbgbAAgoQAAgwAqggQApgiBBAAQASAAAWAIQAAhKhEAAQg0AAgcAcIgYgvQAQgMAcgKQAcgJAZAAQBFAAAfAfQAeAfAABCIAABwQAAAqAZANIAAAcQgiAAgRgJQgRgKgHgWQghAqhFAAQglAAgbgbgAJaBPQgbAWAAAeQAAAxA6AAQAqAAAhgoIAAhMQgbgGgKAAQgqAAgbAVgAFsCBIAAlgIA3AAIAAFXQAAAZAPAOQAOAPAYAAIAAAyQhsAAAAhfgAnFCzQglgsAAhLQAAhHAngsQAngtBAAAQBDAAAlArQAmArAABKQAABMgmAsQgmAshCAAQhDAAgmgtgAmZgXQgXAdAAA2QAAB2BUAAQAnAAAWgfQAWggAAg3QAAhyhTAAQgmAAgXAfgArpC1QgqgsAAhJQAAhJArgtQAsguBLAAQAZAAAcAKQAdALANAKIgcAoQgIgJgVgHQgWgIgVAAQgtAAgbAgQgbAeAAA3QAAA3AcAdQAbAdAwAAQAmAAAmgdIAWAvQgtAdhCAAQhAAAgqgrgAArDaIAAi3QAAgwgPgUQgPgUghAAQgTAAgVALQgVAMgLARIAADnIg4AAIAAk4IAmAAIASAoQAcguA+AAQBlAAAAB8IAADCg");
	this.shape_1.setTransform(-101.8,-1.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180.7,-27,361,48);


(lib.Interpolación4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#091832").s().p("Av7EVIAAmzIA4AAIAAAaQAggfAtAAQBDAAAkApQAmAqAABQQAABGgmAtQglAthHAAQgUAAgWgHQgYgHgGgJIAACMgAuohsQgRAIgKAKIAAC1QAGAIARAHQAQAHAQAAQBoAAAAhzQABg7gagcQgYgcg2AAQgMAAgRAJgAW2CIIAUg1QAvAeAcAAQA0AAgBgrQABgfgygWQgngRgNgIQgNgJgKgMQgKgLgEgNQgGgNAAgPQAAgnAcgWQAdgVAuAAQAhAAA0AVIgPA0QghgbgiAAQgUAAgNAKQgOAJAAAPQAAAeAjAPIAnASQAlARARAUQAQAVABAgQAAAqgfAYQgdAYg1AAQgxAAgsgYgASbCFQgbgbAAgnQAAgwAqgfQAqghBAAAQASAAAWAIQAAhNhEAAQg0AAgcAdIgYgvQAQgNAcgJQAcgJAZAAQBFAAAfAfQAfAfAABDIAABvQgBApAZAOIAAAcQghAAgRgKQgSgKgHgWQghAqhFAAQglAAgbgbgATTAQQgbAWAAAdQAAAxA5AAQAqAAAhgoIAAhMQgagEgLAAQgqAAgaAUgALSB1QgqgrgBhKQAAhJAsgtQAsgtBLAAQAYAAAdAKQAdAKANALIgcAnQgJgIgVgIQgVgIgVAAQgtAAgbAgQgbAgAAA1QAAA4AcAdQAbAcAwAAQAmAAAlgdIAXAvQguAdhCAAQg/AAgqgrgABGB4QgtgsgBhLQABhMAuguQArgqA6AAQBDAAAmAlQAkAlAAA8QAAASgDAOIjjAAQAAA3AeAdQAbAaAqAAQAwAAAggcIAXApQgNAMgaAKQgiAMgpAAQg7AAgqgogABwhcQgYAWgDAiICtAAQABghgWgXQgXgZgnAAQgmAAgZAZgAqTB4QgtgsAAhLQAAhMAuguQArgqA5AAQBDAAAnAlQAkAlAAA8QAAASgDAOIjjAAQAAA3AfAdQAaAaAqAAQAwAAAfgcIAYApQgNAMgaAKQgiAMgpAAQg7AAgqgogApphcQgYAWgDAiICtAAQABghgWgXQgXgZgnAAQgmAAgZAZgA5VB4QgtgsgBhLQABhMAuguQArgqA5AAQBDAAAnAlQAkAlAAA8QAAASgDAOIjjAAQAAA3AeAdQAbAaAqAAQAwAAAfgcIAYApQgNAMgaAKQgiAMgpAAQg7AAgqgogA4rhcQgYAWgDAiICtAAQABghgWgXQgXgZgnAAQgmAAgZAZgAQACaIAAkJIgrAAIAAgvIBiAAIAAE4gAI1CaIAAi0QAAgygPgUQgPgVgkAAQgSAAgVAMQgVALgMARIAADnIg3AAIAAk4IAmAAIARApQAcguA+AAQBoAAAAB9IAADAgAhhCaIAAkJIgrAAIAAgvIBjAAIAAE4gAlhCaIAAk4IA4AAIAAAzQAfg4A7AAQAPAAAcAFIgWA2QgTgNgSAAQgeAAgVAcQgXAbAAAmIAACygAxoCaIhWhyIhMByIhBAAIByieIhoiaIA+AAIBHBsIBOhsIA9AAIhxCaIB8CegAQGjZQgKgLAAgOQAAgOAKgKQAKgKAPAAQAOAAAKAKQAKAKAAAOQAAAOgKALQgKAKgOAAQgOAAgLgKgAhbjZQgKgLAAgOQAAgOAKgKQAKgKAPAAQAOAAAKAKQAKAKAAAOQAAAOgKALQgKAKgOAAQgOAAgLgKg");
	this.shape.setTransform(786.6,4.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ATbEaIAAmzIA3AAIAAAaQAggfAtAAQBDAAAlApQAlAqAABOQAABIglAtQgmAthHAAQgUAAgWgHQgXgHgHgJIAACMgAUthnQgRAIgKAKIAAC1QAGAIARAHQARAHAQAAQBoAAAAh1QAAg5gZgcQgZgcg2AAQgMAAgRAJgAFhEaIAAmzIA4AAIAAAaQAggfAsAAQBDAAAlApQAmAqAABOQAABIgmAtQglAthHAAQgUAAgXgHQgXgHgGgJIAACMgAG0hnQgRAIgKAKIAAC1QAFAIARAHQARAHAQAAQBoAAAAh1QAAg5gZgcQgYgcg2AAQgMAAgRAJgAf7CNIATg1QAvAeAcAAQA0AAAAgrQAAgfgygWQgmgSgNgHQgOgJgKgMQgJgLgFgNQgFgNAAgPQAAgnAcgWQAcgVAuAAQAiAAA0AVIgQA0QghgbghAAQgUAAgOAKQgOAJAAAPQAAAeAjAPIAoASQAkAPARAWQARAVAAAgQAAAqgeAYQgeAYg0AAQgyAAgrgYgAbfCKQgbgbAAgnQAAgwAqgfQAqghBAAAQASAAAWAIQAAhNhEAAQg0AAgcAdIgXgvQAPgNAdgJQAbgJAaAAQBEAAAfAfQAfAfAABDIAABvQAAApAZAOIAAAcQgiAAgRgKQgRgKgHgWQgiAqhFAAQglAAgbgbgAcXAVQgbAWAAAdQAAAxA6AAQAqAAAggoIAAhMQgagFgLAAQgqAAgaAVgAOqB5QgmgsAAhLQAAhHAogtQAngsA/AAQBEAAAlArQAlAqAABLQAABMgmArQgmAshCAAQhDAAglgsgAPWhSQgXAfAAA1QAAB2BTAAQAnAAAXggQAWggAAg2QAAhzhUAAQgmAAgWAfgAhZCNIATg1QAvAeAaAAQA0AAAAgrQAAgfgygWQgkgSgNgHQgOgJgKgMQgJgLgFgNQgFgNAAgPQAAgnAcgWQAcgVAsAAQAiAAA0AVIgQA0QghgbghAAQgSAAgOAKQgOAJAAAPQAAAeAhAPIAoASQAkAPARAWQARAVAAAgQAAAqgeAYQgeAYg0AAQgwAAgrgYgAl0CIQgcgeAAg3IAAjMIA4AAIAADHQAABIA/AAQAcAAAWgQQAXgPAIgVIAAjbIA3AAIAAE4Ig3AAIAAgrQgKASgcAQQgcAPgbAAQg0AAgbgdgAqUCNIATg1QAvAeAcAAQA0AAAAgrQAAgfgygWQgmgSgNgHQgOgJgKgMQgJgLgFgNQgFgNAAgPQAAgnAcgWQAcgVAuAAQAiAAA0AVIgQA0QghgbghAAQgUAAgOAKQgOAJAAAPQAAAeAjAPIAoASQAkAPARAWQARAVAAAgQAAAqgeAYQgeAYg0AAQgyAAgrgYgAxlCKQgbgbAAgnQAAgwAqgfQAqghBAAAQASAAAWAIQAAhNhEAAQg0AAgcAdIgXgvQAPgNAdgJQAbgJAaAAQBEAAAfAfQAfAfAABDIAABvQAAApAZAOIAAAcQgiAAgRgKQgRgKgHgWQgiAqhFAAQglAAgbgbgAwtAVQgbAWAAAdQAAAxA6AAQAqAAAggoIAAhMQgagFgLAAQgqAAgaAVgA4uB6QgqgrAAhKQAAhJArgtQAsgtBLAAQAZAAAcAKQAdAKANALIgcAnQgIgIgVgIQgWgIgVAAQgtAAgbAgQgbAgAAA1QAAA4AcAdQAbAcAwAAQAmAAAmgdIAWAvQgtAdhCAAQhAAAgqgrgA90CKQgbgbAAgnQAAgwAqgfQAqghBAAAQASAAAWAIQAAhNhEAAQg0AAgcAdIgXgvQAPgNAdgJQAbgJAaAAQBEAAAfAfQAfAfAABDIAABvQAAApAZAOIAAAcQgiAAgRgKQgRgKgHgWQgiAqhFAAQglAAgbgbgA88AVQgbAWAAAdQAAAxA6AAQAqAAAggoIAAhMQgagFgLAAQgqAAgaAVgAZECfIAAkJIgrAAIAAgvIBjAAIAAE4gAK0CfIAAk4IA4AAIAAAzQAeg4A8AAQAPAAAcAFIgXA2QgSgNgSAAQgeAAgWAcQgWAbAAAmIAACygA0ACfIAAkJIgrAAIAAgvIBjAAIAAE4gEggFACfIAAjDQAAgjgSgUQgRgVgfAAQgUAAgVANQgUALgLAQIAADnIg4AAIAAm4IA4AAIAACjQALgRAZgMQAZgLAaAAQAyAAAcAgQAcAhAAA5IAADDgAZLjUQgLgLAAgOQAAgOAKgKQAKgKAPAAQAOAAAKAKQAKAKAAAOQAAAOgKALQgKAKgOAAQgOAAgKgKgAz5jUQgLgLAAgOQAAgOAKgKQAKgKAPAAQAOAAAKAKQAKAKAAAOQAAAOgKALQgKAKgOAAQgOAAgKgKg");
	this.shape_1.setTransform(373,4.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(148.2,-23.9,805.2,56.6);


(lib.Interpolación2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AZWDHIATg1QAvAfAcAAQA0AAgBgsQABgfgygWQgngSgMgJQgOgJgKgLQgKgMgEgNQgGgLAAgPQAAgnAcgVQAdgWAtAAQAjAAA0AWIgQAzQghgaghAAQgVAAgNAJQgOAKAAAOQAAAcAiAQIApASQAkARARAVQARAVAAAhQAAAqgfAYQgdAYg1AAQgxAAgrgZgAU5CzQgmgsAAhLQAAhHAogsQAngtBAAAQBDAAAlArQAmArAABKQAABMgnAsQglAshCAAQhDAAgmgtgAVlgXQgXAdAAA2QAAB2BUAAQAnAAAWgfQAWggAAg3QAAhyhTAAQgnAAgWAfgAC/DCQgcgeAAg2IAAjMIA4AAIAADGQAABJA/AAQAbAAAXgQQAXgQAIgVIAAjaIA3AAIAAE4Ig3AAIAAgsQgKATgcAPQgcAQgbAAQg0AAgbgegAgECBIAAlgIA1AAIAAFXQABAZAPAOQAOAPAXAAIAAAyQhqAAAAhfgAk4DFQgbgbAAgoQgBgwAqggQAqgiBAAAQATAAAWAIQAAhKhFAAQg0AAgcAcIgXgvQAPgMAdgKQAbgJAaAAQBEAAAfAfQAfAfAABCIAABwQAAAqAZANIAAAcQgiAAgRgJQgRgKgHgWQgiAqhEAAQgmAAgagbgAkBBPQgbAWAAAeQAAAxA6AAQAqAAAhgoIAAhMQgbgGgKAAQgrAAgaAVgAsADHIATg1QAwAfAcAAQAzAAAAgsQAAgfgxgWQgngSgNgJQgOgJgJgLQgKgMgFgNQgFgLAAgPQAAgnAcgVQAdgWAtAAQAiAAA0AWIgPAzQgigaghAAQgUAAgOAJQgOAKABAOQAAAcAiAQIAoASQAkARARAVQARAVAAAhQAAAqgeAYQgdAYg1AAQgyAAgrgZgAwbDCQgbgeAAg2IAAjMIA4AAIAADGQgBBJBAAAQAbAAAWgQQAYgQAHgVIAAjaIA3AAIAAE4Ig3AAIAAgsQgJATgcAPQgdAQgbAAQg0AAgbgegAzzDEQgagcAAgqIAAiwIglAAIAAgsIAlAAIAAhCIA3gVIAABXIBXAAIAAAsIhXAAIAACaQAAAnANARQAOARAdAAQAWAAAWgLIAJAxQgjAJgpAAQglAAgZgcgA8GDFQgbgbAAgoQAAgwApggQAqgiBAAAQASAAAXAIQAAhKhFAAQg0AAgcAcIgXgvQAQgMAcgKQAcgJAZAAQBFAAAeAfQAfAfAABCIAABwQAAAqAZANIAAAcQgiAAgRgJQgRgKgHgWQgiAqhEAAQglAAgbgbgA7PBPQgbAWAAAeQAAAxA6AAQAqAAAhgoIAAhMQgbgGgLAAQgqAAgaAVgAShDaIAAi3QAAgwgPgUQgPgUgkAAQgTAAgUALQgVAMgMARIAADnIg3AAIAAk4IAmAAIARAoQAdguA9AAQBoAAAAB8IAADCgANZDaIAAjHQAAhIhAAAQgUAAgRANQgSAMgGAQIAADmIg4AAIAAjdQgBgXgQgOQgSgNgdAAQgRAAgSANQgUANgHAPIAADmIg4AAIAAk4IAlAAIASAkQAggqAxAAQBDAAAaAqQAKgSAagMQAZgMAbAAQAxAAAaAdQAbAdAAAyIAADSg");
	this.shape.setTransform(-16.9,-1.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#091832").s().p("AoWC0Qgzg8AAhkQAAhiA4g+QA4g+BgAAQBDAAArAlIgZAxQgsghgqAAQhEAAgnAvQgnAwAABMQAABLAnAtQAmAtBCAAQAuAAAdgcIAAhkIg7AAIAAgyIB2AAIAAC7QgXAUgqAMQgqAMgoAAQhYAAg0g8gAFZDUQgbgbAAgoQAAgwAqggQApgiBBAAQASAAAWAIQAAhKhEAAQg0AAgcAcIgYgvQAQgMAcgKQAcgJAZAAQBFAAAfAfQAeAfAABCIAABwQAAAqAZANIAAAcQgiAAgRgJQgRgKgHgWQghAqhFAAQglAAgbgbgAGQBeQgbAWAAAeQAAAxA6AAQAqAAAhgoIAAhMQgbgGgKAAQgqAAgbAVgAiLDRQgbgeAAg2IAAjMIA4AAIAADGQAABJA/AAQAbAAAVgQQAXgQAHgVIAAjaIA4AAIAAE4Ig4AAIAAgsQgJATgaAPQgdAQgbAAQgzAAgcgegAC+DpIAAkJIgrAAIAAgvIBjAAIAAE4gACuiOIAyhhIA5AAIhCBhg");
	this.shape_1.setTransform(-281.1,-3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-339.7,-27,505.5,48.2);


(lib.Interpolación25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.6)").s().p("AgkD7QgEgBgDgDQgCgEAAgEQABgEADgCQAEgDAEABQARACAQAAIAVgBQAEAAADACQAEADAAAEQAAAEgCAEQgDADgEAAIgXABIAAAAQgSAAgSgCgABPDuQgEgCgCgEQgBgEACgDQACgEAEgBQAbgKAYgRQADgCAEABQAEAAACADIABABQACADgBAEQAAAEgEADQgaASgeALIgDAAIgEgBgAhgDqQgdgLgZgUQgEgDAAgEQgBgEADgDQADgDAEgBQAEgBADADQAYASAaALQAEABABAEQACAEgCAEQgBAEgEABIgEABIgEgBgACtCrIgBAAQgCgDAAgEQgBgEADgDQAUgWAOgZQACgEAEgBQAEgBADACQAEACABAEQABAEgCADQgOAbgWAYQgDADgEABIgBAAQgDAAgDgDgAi7ClQgEAAgDgDQgUgZgNgbQgCgEABgEQABgEAEgBQAEgCAEABQAEABACAEQALAZATAXQADADAAAEQAAAEgEADQgCACgEAAIgBAAgADpBFQgDgBgDgEQgCgDABgEQAHgcAAgdQAAgDADgCQADgDAEAAIAAAAQAEAAADADQADACAAADQAAAggHAeQgBADgEADQgCABgDAAIgDAAgAjzA5QgDgDgBgDQgFgZAAgaIABgNQAAgEADgCQADgDAEAAIAAAAQAEAAADAEQADADgBAEIAAALQAAAYAEAXQABAEgCADQgDADgDABIgDAAQgCAAgDgBgADrgXQgDgDgBgEQgEgegKgbQgCgEACgDQABgEAEgBIAAgBQAEgBAEABQAEACABAEQAMAdAEAgQABAEgDAEQgDADgEABIAAAAIgBAAQgDAAgDgCgAjqg9IAAAAQgEgBgCgEQgCgDABgEQAJgeAQgbQACgEAEgBQAEgBADADIABAAQADACABAEQABADgCAEQgPAZgIAbQgBAEgEACIgEABIgDAAgADDiFQgEgBgDgDQgLgOgNgNIgOgNQgDgDgBgEQAAgEADgDIAAAAQADgEAEAAQAEAAADADIAPAOQAPAOALAPQADADgBAEQgBAEgDADIAAAAQgDACgDAAIgBAAgAiyikIAAAAQgDgDAAgEQAAgEADgDQAXgXAagPQADgDAEABQAEABACAEQADAEgBAEQgBADgEADQgYAOgVAVQgDADgEAAQgEAAgDgDgABmjRQgagMgdgGQgDgBgDgDQgCgEABgEQABgEADgCQADgDAFABQAfAGAcAOQAEACABAEQABAEgCADIAAABQgBADgEACIgDAAIgFgBgAhKjgQgEgCgBgDIAAgBQgBgEACgDQACgEAEgBQAdgIAhgCQAEAAADADQADACAAAFIAAAAQAAAEgCADQgDADgEAAQgeABgcAIIgCABIgFgCg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.498)").s().p("AAcDrQgDgCgEAAIgVABQgRAAgQgCQgFgBgDACQgDADgBAEQgUgEgSgGQABgEgBgEQgCgEgEgBQgagLgXgSQgDgDgFABQgEABgCADIgTgSIgJgJQADgCABgEQAAgEgDgDQgTgXgMgZQgCgEgEgBQgDgBgEABQgIgSgFgUQAEgBACgDQADgDgBgFQgEgWAAgZIAAgKQAAgEgCgEQgDgDgEAAIAAAAQABgUAFgTIAAAAQAEABAEgCQADgCACgEQAIgbAPgZQACgEgBgDQgBgEgEgCQALgQAOgPQADADAEAAQAEAAADgDQAVgVAYgOQADgDABgEQABgDgCgEQASgKATgGQABADADACQAEACAEgBQAbgIAfgBQAEAAADgDQACgDAAgEIAAAAQAUAAATADQAAAEACADQACAEAEABQAdAGAaAMQAEACADgBQAEgCACgEQARAKAQANQgCADAAAEQAAAEAEACIAOAOQANANALAOQACADAEABQAEABADgDQAMARAIASQgDACgCAEQgBADABAEQALAbAEAeQAAAEAEACQADADAEAAIAAAMQgEABgCACQgDADAAACQAAAegHAcQgBAEACADQACAEAEABQgFATgJASQgEgCgEABQgEABgCAEQgNAZgUAWQgDADAAAEQAAAEADADIgBAAQgNAOgOAKQgCgDgEAAQgEgBgEACQgXARgcAKQgEABgBAEQgCADABAEQgUAGgVADQgBgEgDgDg");
	this.shape_1.setTransform(0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.3,-25.3,50.7,50.7);


(lib.Interpolación23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(255,255,255,0.6)").ss(2).p("ADzAAQAABkhHBHQhHBIhlAAQhkAAhHhIQhHhHAAhkQAAhkBHhHQBHhHBkAAQBlAABHBHQBHBHAABkg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.498)").s().p("AirCrQhHhGAAhlQAAhjBHhIQBIhHBjAAQBlAABGBHQBIBIAABjQAABlhIBGQhGBIhlAAQhjAAhIhIg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.3,-25.3,50.7,50.7);


(lib.Interpolación22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.6)").s().p("AgkD7QgEgBgDgDQgCgEAAgEQABgEADgCQAEgDAEABQARACAQAAIAVgBQAEAAADACQAEADAAAEQAAAEgCAEQgDADgEAAIgXABIAAAAQgSAAgSgCgABPDuQgEgCgCgEQgBgEACgDQACgEAEgBQAbgKAYgRQADgCAEABQAEAAACADIABABQACADgBAEQAAAEgEADQgaASgeALIgDAAIgEgBgAhgDqQgdgLgZgUQgEgDAAgEQgBgEADgDQADgDAEgBQAEgBADADQAYASAaALQAEABABAEQACAEgCAEQgBAEgEABIgEABIgEgBgACtCrIgBAAQgCgDAAgEQgBgEADgDQAUgWAOgZQACgEAEgBQAEgBADACQAEACABAEQABAEgCADQgOAbgWAYQgDADgEABIgBAAQgDAAgDgDgAi7ClQgEAAgDgDQgUgZgNgbQgCgEABgEQABgEAEgBQAEgCAEABQAEABACAEQALAZATAXQADADAAAEQAAAEgEADQgCACgEAAIgBAAgADpBFQgDgBgDgEQgCgDABgEQAHgcAAgdQAAgDADgCQADgDAEAAIAAAAQAEAAADADQADACAAADQAAAggHAeQgBADgEADQgCABgDAAIgDAAgAjzA5QgDgDgBgDQgFgZAAgaIABgNQAAgEADgCQADgDAEAAIAAAAQAEAAADAEQADADgBAEIAAALQAAAYAEAXQABAEgCADQgDADgDABIgDAAQgCAAgDgBgADrgXQgDgDgBgEQgEgegKgbQgCgEACgDQABgEAEgBIAAgBQAEgBAEABQAEACABAEQAMAdAEAgQABAEgDAEQgDADgEABIAAAAIgBAAQgDAAgDgCgAjqg9IAAAAQgEgBgCgEQgCgDABgEQAJgeAQgbQACgEAEgBQAEgBADADIABAAQADACABAEQABADgCAEQgPAZgIAbQgBAEgEACIgEABIgDAAgADDiFQgEgBgDgDQgLgOgNgNIgOgNQgDgDgBgEQAAgEADgDIAAAAQADgEAEAAQAEAAADADIAPAOQAPAOALAPQADADgBAEQgBAEgDADIAAAAQgDACgDAAIgBAAgAiyikIAAAAQgDgDAAgEQAAgEADgDQAXgXAagPQADgDAEABQAEABACAEQADAEgBAEQgBADgEADQgYAOgVAVQgDADgEAAQgEAAgDgDgABmjRQgagMgdgGQgDgBgDgDQgCgEABgEQABgEADgCQADgDAFABQAfAGAcAOQAEACABAEQABAEgCADIAAABQgBADgEACIgDAAIgFgBgAhKjgQgEgCgBgDIAAgBQgBgEACgDQACgEAEgBQAdgIAhgCQAEAAADADQADACAAAFIAAAAQAAAEgCADQgDADgEAAQgeABgcAIIgCABIgFgCg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.498)").s().p("AAcDrQgDgCgEAAIgVABQgRAAgQgCQgFgBgDACQgDADgBAEQgUgEgSgGQABgEgBgEQgCgEgEgBQgagLgXgSQgDgDgFABQgEABgCADIgTgSIgJgJQADgCABgEQAAgEgDgDQgTgXgMgZQgCgEgEgBQgDgBgEABQgIgSgFgUQAEgBACgDQADgDgBgFQgEgWAAgZIAAgKQAAgEgCgEQgDgDgEAAIAAAAQABgUAFgTIAAAAQAEABAEgCQADgCACgEQAIgbAPgZQACgEgBgDQgBgEgEgCQALgQAOgPQADADAEAAQAEAAADgDQAVgVAYgOQADgDABgEQABgDgCgEQASgKATgGQABADADACQAEACAEgBQAbgIAfgBQAEAAADgDQACgDAAgEIAAAAQAUAAATADQAAAEACADQACAEAEABQAdAGAaAMQAEACADgBQAEgCACgEQARAKAQANQgCADAAAEQAAAEAEACIAOAOQANANALAOQACADAEABQAEABADgDQAMARAIASQgDACgCAEQgBADABAEQALAbAEAeQAAAEAEACQADADAEAAIAAAMQgEABgCACQgDADAAACQAAAegHAcQgBAEACADQACAEAEABQgFATgJASQgEgCgEABQgEABgCAEQgNAZgUAWQgDADAAAEQAAAEADADIgBAAQgNAOgOAKQgCgDgEAAQgEgBgEACQgXARgcAKQgEABgBAEQgCADABAEQgUAGgVADQgBgEgDgDg");
	this.shape_1.setTransform(0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.3,-25.3,50.7,50.7);


(lib.Interpolación21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.6)").s().p("AgkD7QgEgBgDgDQgCgEAAgEQABgEADgCQAEgDAEABQARACAQAAIAVgBQAEAAADACQAEADAAAEQAAAEgCAEQgDADgEAAIgXABIAAAAQgSAAgSgCgABPDuQgEgCgCgEQgBgEACgDQACgEAEgBQAbgKAYgRQADgCAEABQAEAAACADIABABQACADgBAEQAAAEgEADQgaASgeALIgDAAIgEgBgAhgDqQgdgLgZgUQgEgDAAgEQgBgEADgDQADgDAEgBQAEgBADADQAYASAaALQAEABABAEQACAEgCAEQgBAEgEABIgEABIgEgBgACtCrIgBAAQgCgDAAgEQgBgEADgDQAUgWAOgZQACgEAEgBQAEgBADACQAEACABAEQABAEgCADQgOAbgWAYQgDADgEABIgBAAQgDAAgDgDgAi7ClQgEAAgDgDQgUgZgNgbQgCgEABgEQABgEAEgBQAEgCAEABQAEABACAEQALAZATAXQADADAAAEQAAAEgEADQgCACgEAAIgBAAgADpBFQgDgBgDgEQgCgDABgEQAHgcAAgdQAAgDADgCQADgDAEAAIAAAAQAEAAADADQADACAAADQAAAggHAeQgBADgEADQgCABgDAAIgDAAgAjzA5QgDgDgBgDQgFgZAAgaIABgNQAAgEADgCQADgDAEAAIAAAAQAEAAADAEQADADgBAEIAAALQAAAYAEAXQABAEgCADQgDADgDABIgDAAQgCAAgDgBgADrgXQgDgDgBgEQgEgegKgbQgCgEACgDQABgEAEgBIAAgBQAEgBAEABQAEACABAEQAMAdAEAgQABAEgDAEQgDADgEABIAAAAIgBAAQgDAAgDgCgAjqg9IAAAAQgEgBgCgEQgCgDABgEQAJgeAQgbQACgEAEgBQAEgBADADIABAAQADACABAEQABADgCAEQgPAZgIAbQgBAEgEACIgEABIgDAAgADDiFQgEgBgDgDQgLgOgNgNIgOgNQgDgDgBgEQAAgEADgDIAAAAQADgEAEAAQAEAAADADIAPAOQAPAOALAPQADADgBAEQgBAEgDADIAAAAQgDACgDAAIgBAAgAiyikIAAAAQgDgDAAgEQAAgEADgDQAXgXAagPQADgDAEABQAEABACAEQADAEgBAEQgBADgEADQgYAOgVAVQgDADgEAAQgEAAgDgDgABmjRQgagMgdgGQgDgBgDgDQgCgEABgEQABgEADgCQADgDAFABQAfAGAcAOQAEACABAEQABAEgCADIAAABQgBADgEACIgDAAIgFgBgAhKjgQgEgCgBgDIAAgBQgBgEACgDQACgEAEgBQAdgIAhgCQAEAAADADQADACAAAFIAAAAQAAAEgCADQgDADgEAAQgeABgcAIIgCABIgFgCg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.498)").s().p("AAcDrQgDgCgEAAIgVABQgRAAgQgCQgFgBgDACQgDADgBAEQgUgEgSgGQABgEgBgEQgCgEgEgBQgagLgXgSQgDgDgFABQgEABgCADIgTgSIgJgJQADgCABgEQAAgEgDgDQgTgXgMgZQgCgEgEgBQgDgBgEABQgIgSgFgUQAEgBACgDQADgDgBgFQgEgWAAgZIAAgKQAAgEgCgEQgDgDgEAAIAAAAQABgUAFgTIAAAAQAEABAEgCQADgCACgEQAIgbAPgZQACgEgBgDQgBgEgEgCQALgQAOgPQADADAEAAQAEAAADgDQAVgVAYgOQADgDABgEQABgDgCgEQASgKATgGQABADADACQAEACAEgBQAbgIAfgBQAEAAADgDQACgDAAgEIAAAAQAUAAATADQAAAEACADQACAEAEABQAdAGAaAMQAEACADgBQAEgCACgEQARAKAQANQgCADAAAEQAAAEAEACIAOAOQANANALAOQACADAEABQAEABADgDQAMARAIASQgDACgCAEQgBADABAEQALAbAEAeQAAAEAEACQADADAEAAIAAAMQgEABgCACQgDADAAACQAAAegHAcQgBAEACADQACAEAEABQgFATgJASQgEgCgEABQgEABgCAEQgNAZgUAWQgDADAAAEQAAAEADADIgBAAQgNAOgOAKQgCgDgEAAQgEgBgEACQgXARgcAKQgEABgBAEQgCADABAEQgUAGgVADQgBgEgDgDg");
	this.shape_1.setTransform(0,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-25.3,-25.3,50.7,50.7);


(lib.Interpolación19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AA4A40").s().p("AomIoQjljlAAlDQAAlCDljkQDkjlFCAAQFDAADkDlQDlDkAAFCQAAFDjlDlQjkDklDAAQlCAAjkjkg");
	this.shape.setTransform(0,0,1.14,0.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88.9,-40.9,177.9,81.9);


(lib.Interpolación15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(204,204,204,0.929)").s().p("AqLIoQhkhmgaiXQgMhHAAjkQAAjjAMhHQAaiYBkhkQCzizHYAAQHZAACyCzQBmBkAZCYQAMBHAADjQAADkgMBHQgZCXhmBmQiyCynZAAQnYAAiziyg");
	this.shape.setTransform(0,0,0.626,0.079);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.5,-5.7,99,11.6);


(lib.Interpolación14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2).p("AMWAAQAAA6gMASQgZAohlAaQizAunZAAQnYAAizguQhlgagZgoQgMgSAAg6QAAg6AMgSQAZgnBlgaQCzguHYAAQHZAACzAuQBlAaAZAnQAMASAAA6g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.1,-19.8,168.2,39.7);


(lib.Interpolación13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2).p("AMWAAQAAA6gMASQgZAohlAaQizAunZAAQnYAAizguQhlgagZgoQgMgSAAg6QAAg6AMgSQAZgnBlgaQCzguHYAAQHZAACzAuQBlAaAZAnQAMASAAA6g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.1,-19.8,168.2,39.7);


(lib.transicion_nubes_on = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_168 = function() {
		this.parent.gotoAndStop("inicio");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(168).call(this.frame_168).wait(1));

	// texto1
	this.instance = new lib.Interpolación2("synched",0);
	this.instance.setTransform(634.1,421.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({_off:false},0).to({alpha:1},15).wait(120).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// texto2
	this.instance_1 = new lib.Interpolación4("synched",0);
	this.instance_1.setTransform(669.2,421.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(43).to({_off:false},0).to({alpha:1},13).wait(93).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// texto3
	this.instance_2 = new lib.Interpolación6("synched",0);
	this.instance_2.setTransform(959.2,529.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(83).to({_off:false},0).to({alpha:1},13).wait(53).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// linea1
	this.instance_3 = new lib.linea_textos();
	this.instance_3.setTransform(-596.7,447.1,1,1,0,0,0,584.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({x:-558},0).wait(1).to({x:-519.3},0).wait(1).to({x:-480.6},0).wait(1).to({x:-441.9},0).wait(1).to({x:-403.3},0).wait(1).to({x:-364.6},0).wait(1).to({x:-325.9},0).wait(1).to({x:-287.2},0).wait(1).to({x:-248.5},0).wait(1).to({x:-209.9},0).wait(1).to({x:-171.2},0).wait(1).to({x:-132.5},0).wait(1).to({x:-93.8},0).wait(1).to({x:-55.2},0).wait(1).to({x:-16.5},0).wait(1).to({x:22.2},0).wait(1).to({x:60.9},0).wait(1).to({x:99.6},0).wait(1).to({x:138.2},0).wait(1).to({x:176.9},0).wait(1).to({x:215.6},0).wait(118).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// linea2
	this.instance_4 = new lib.linea_textos();
	this.instance_4.setTransform(2533.2,447.1,1,1,0,0,0,584.6,0);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(29).to({_off:false},0).wait(1).to({x:2479.4},0).wait(1).to({x:2425.5},0).wait(1).to({x:2371.7},0).wait(1).to({x:2317.9},0).wait(1).to({x:2264.1},0).wait(1).to({x:2210.2},0).wait(1).to({x:2156.5},0).wait(1).to({x:2102.6},0).wait(1).to({x:2048.8},0).wait(1).to({x:1994.9},0).wait(1).to({x:1941.1},0).wait(1).to({x:1887.3},0).wait(1).to({x:1833.5},0).wait(1).to({x:1779.7},0).wait(1).to({x:1725.8},0).wait(1).to({x:1672},0).wait(1).to({x:1618.2},0).wait(1).to({x:1564.3},0).wait(1).to({x:1510.5},0).wait(1).to({x:1456.7},0).wait(1).to({x:1402.9},0).wait(89).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// linea3
	this.instance_5 = new lib.linea_textos();
	this.instance_5.setTransform(-590.7,555.2,1,1,0,0,0,584.6,0);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(72).to({_off:false},0).wait(1).to({x:-523.2},0).wait(1).to({x:-455.7},0).wait(1).to({x:-388.2},0).wait(1).to({x:-320.7},0).wait(1).to({x:-253.2},0).wait(1).to({x:-185.7},0).wait(1).to({x:-118.2},0).wait(1).to({x:-50.7},0).wait(1).to({x:16.7},0).wait(1).to({x:84.2},0).wait(1).to({x:151.7},0).wait(1).to({x:219.2},0).wait(1).to({x:286.7},0).wait(1).to({x:354.2},0).wait(1).to({x:421.7},0).wait(1).to({x:489.2},0).wait(1).to({x:556.6},0).wait(50).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// Capa 9
	this.instance_6 = new lib.Símbolo6();
	this.instance_6.setTransform(718.1,427.5,1,1,0,0,0,473.4,271.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(132).to({regX:414.2,regY:259.7,x:688.9,y:438.1},0).wait(1).to({x:718.9,y:460.7},0).wait(1).to({x:749,y:483.3},0).wait(1).to({x:779,y:505.9},0).wait(1).to({x:809.1,y:528.5},0).wait(1).to({x:839.1,y:551.1},0).wait(1).to({x:869.1,y:573.7},0).wait(1).to({x:899.2,y:596.3},0).wait(1).to({x:929.2,y:618.9},0).wait(1).to({x:959.3,y:641.5},0).wait(1).to({x:989.3,y:664.1},0).wait(1).to({x:1019.3,y:686.7},0).wait(1).to({x:1049.4,y:709.3},0).wait(1).to({x:1079.4,y:731.9},0).wait(1).to({x:1109.5,y:754.5},0).wait(1).to({x:1139.5,y:777.1},0).wait(1).to({x:1169.5,y:799.7},0).wait(1).to({x:1199.6,y:822.3},0).wait(1).to({x:1229.6,y:844.9},0).wait(1).to({x:1259.7,y:867.5},0).wait(1).to({x:1289.7,y:890.1},0).wait(1).to({x:1319.7,y:912.7},0).wait(1).to({x:1349.8,y:935.3},0).wait(1).to({x:1379.8,y:957.9},0).wait(1).to({x:1409.8,y:980.5},0).wait(1).to({x:1439.9,y:1003.1},0).wait(1).to({x:1469.9,y:1025.7},0).wait(1).to({x:1500,y:1048.3},0).wait(1).to({x:1530,y:1070.9},0).wait(1).to({x:1560.1,y:1093.5},0).wait(1).to({x:1590.1,y:1116.1},0).wait(1).to({x:1620.1,y:1138.7},0).wait(1).to({x:1650.2,y:1161.3},0).wait(1).to({x:1680.2,y:1183.9},0).wait(1).to({x:1710.3,y:1206.5},0).wait(1).to({x:1740.3,y:1229.2},0).to({_off:true},1).wait(1));

	// Capa 8
	this.instance_7 = new lib.Símbolo5();
	this.instance_7.setTransform(1070.3,714.7,1,1,0,0,0,281.4,178.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(132).to({regX:281.5,x:1041.5,y:693.8},0).wait(1).to({x:1012.7,y:672.9},0).wait(1).to({x:983.9,y:652.1},0).wait(1).to({x:955.1,y:631.2},0).wait(1).to({x:926.3,y:610.3},0).wait(1).to({x:897.4,y:589.5},0).wait(1).to({x:868.6,y:568.6},0).wait(1).to({x:839.8,y:547.7},0).wait(1).to({x:811,y:526.9},0).wait(1).to({x:782.2,y:506},0).wait(1).to({x:753.4,y:485.1},0).wait(1).to({x:724.5,y:464.3},0).wait(1).to({x:695.7,y:443.4},0).wait(1).to({x:666.9,y:422.6},0).wait(1).to({x:638.1,y:401.7},0).wait(1).to({x:609.3,y:380.8},0).wait(1).to({x:580.4,y:360},0).wait(1).to({x:551.6,y:339.1},0).wait(1).to({x:522.8,y:318.2},0).wait(1).to({x:494,y:297.4},0).wait(1).to({x:465.2,y:276.5},0).wait(1).to({x:436.4,y:255.6},0).wait(1).to({x:407.5,y:234.8},0).wait(1).to({x:378.7,y:213.9},0).wait(1).to({x:349.9,y:193.1},0).wait(1).to({x:321.1,y:172.2},0).wait(1).to({x:292.3,y:151.4},0).wait(1).to({x:263.5,y:130.5},0).wait(1).to({x:234.7,y:109.6},0).wait(1).to({x:205.9,y:88.8},0).wait(1).to({x:177,y:67.9},0).wait(1).to({x:148.2,y:47.1},0).wait(1).to({x:119.4,y:26.2},0).wait(1).to({x:90.6,y:5.3},0).wait(1).to({x:61.8,y:-15.5},0).wait(1).to({x:32.9,y:-36.4},0).to({_off:true},1).wait(1));

	// Capa 7
	this.instance_8 = new lib.Símbolo3();
	this.instance_8.setTransform(678.7,534.2,1,1,0,0,0,1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(132).to({x:630.1,y:499.5},0).wait(1).to({x:581.5,y:464.9},0).wait(1).to({x:533,y:430.2},0).wait(1).to({x:484.4,y:395.5},0).wait(1).to({x:435.8,y:360.9},0).wait(1).to({x:387.2,y:326.2},0).wait(1).to({x:338.7,y:291.6},0).wait(1).to({x:290.1,y:256.9},0).wait(1).to({x:241.5,y:222.2},0).wait(1).to({x:192.9,y:187.6},0).wait(1).to({x:144.3,y:152.9},0).wait(1).to({x:95.8,y:118.2},0).wait(1).to({x:47.2,y:83.6},0).wait(1).to({x:-1.3,y:49},0).wait(1).to({x:-50,y:14.3},0).wait(1).to({x:-98.5,y:-20.4},0).wait(1).to({x:-147.1,y:-55.1},0).wait(1).to({x:-195.7,y:-89.7},0).wait(1).to({x:-244.3,y:-124.4},0).wait(1).to({x:-292.9,y:-159.1},0).wait(1).to({x:-341.4,y:-193.7},0).wait(1).to({x:-390,y:-228.4},0).wait(1).to({x:-438.6,y:-263},0).wait(1).to({x:-487.2,y:-297.7},0).wait(1).to({x:-535.7,y:-332.4},0).wait(1).to({x:-584.3,y:-367},0).wait(1).to({x:-632.9,y:-401.7},0).to({_off:true},1).wait(10));

	// Capa 1
	this.instance_9 = new lib.Símbolo4();
	this.instance_9.setTransform(1286.2,816.3,1,1,0,0,0,1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(132).to({regY:1081.6,x:1328.7,y:843.4},0).wait(1).to({x:1371.1,y:870.5},0).wait(1).to({x:1413.5,y:897.7},0).wait(1).to({x:1455.9,y:924.8},0).wait(1).to({x:1498.4,y:952},0).wait(1).to({x:1540.8,y:979.1},0).wait(1).to({x:1583.2,y:1006.2},0).wait(1).to({x:1625.7,y:1033.4},0).wait(1).to({x:1668.1,y:1060.6},0).wait(1).to({x:1710.5,y:1087.7},0).wait(1).to({x:1752.9,y:1114.8},0).wait(1).to({x:1795.4,y:1142},0).wait(1).to({x:1837.8,y:1169.1},0).wait(1).to({x:1880.2,y:1196.2},0).wait(1).to({x:1922.7,y:1223.4},0).wait(1).to({x:1965.1,y:1250.6},0).wait(1).to({x:2007.5,y:1277.7},0).wait(1).to({x:2050,y:1304.9},0).wait(1).to({x:2092.4,y:1332},0).wait(1).to({x:2134.8,y:1359.2},0).wait(1).to({x:2177.3,y:1386.3},0).wait(1).to({x:2219.7,y:1413.5},0).wait(1).to({x:2262.1,y:1440.6},0).wait(1).to({x:2304.6,y:1467.8},0).wait(1).to({x:2347,y:1494.9},0).wait(1).to({x:2389.4,y:1522.1},0).wait(1).to({x:2431.9,y:1549.3},0).to({_off:true},1).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1182.8,-547.5,3879.9,2445.4);


(lib.transicion_nubes_off = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{play:0});

	// timeline functions:
	this.frame_36 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(36).call(this.frame_36).wait(1));

	// Capa 9
	this.instance = new lib.Símbolo6();
	this.instance.setTransform(1799.5,1241.2,1,1,0,0,0,473.4,271.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:414.2,regY:259.7,x:1710.3,y:1206.5},0).wait(1).to({x:1680.2,y:1183.9},0).wait(1).to({x:1650.2,y:1161.3},0).wait(1).to({x:1620.1,y:1138.7},0).wait(1).to({x:1590.1,y:1116.1},0).wait(1).to({x:1560.1,y:1093.5},0).wait(1).to({x:1530,y:1070.9},0).wait(1).to({x:1500,y:1048.3},0).wait(1).to({x:1469.9,y:1025.7},0).wait(1).to({x:1439.9,y:1003.1},0).wait(1).to({x:1409.9,y:980.5},0).wait(1).to({x:1379.8,y:957.9},0).wait(1).to({x:1349.8,y:935.3},0).wait(1).to({x:1319.7,y:912.7},0).wait(1).to({x:1289.7,y:890.1},0).wait(1).to({x:1259.7,y:867.5},0).wait(1).to({x:1229.6,y:844.9},0).wait(1).to({x:1199.6,y:822.3},0).wait(1).to({x:1169.5,y:799.7},0).wait(1).to({x:1139.5,y:777.1},0).wait(1).to({x:1109.5,y:754.5},0).wait(1).to({x:1079.4,y:731.9},0).wait(1).to({x:1049.4,y:709.3},0).wait(1).to({x:1019.3,y:686.7},0).wait(1).to({x:989.3,y:664.1},0).wait(1).to({x:959.3,y:641.5},0).wait(1).to({x:929.2,y:618.9},0).wait(1).to({x:899.2,y:596.3},0).wait(1).to({x:869.1,y:573.7},0).wait(1).to({x:839.1,y:551.1},0).wait(1).to({x:809.1,y:528.5},0).wait(1).to({x:779,y:505.9},0).wait(1).to({x:749,y:483.3},0).wait(1).to({x:718.9,y:460.7},0).wait(1).to({x:688.9,y:438.1},0).wait(1).to({x:658.9,y:415.5},0).wait(1));

	// Capa 8
	this.instance_1 = new lib.Símbolo5();
	this.instance_1.setTransform(32.8,-36.4,1,1,0,0,0,281.4,178.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:281.5,x:61.8,y:-15.5},0).wait(1).to({x:90.6,y:5.3},0).wait(1).to({x:119.4,y:26.2},0).wait(1).to({x:148.2,y:47.1},0).wait(1).to({x:177,y:67.9},0).wait(1).to({x:205.9,y:88.8},0).wait(1).to({x:234.7,y:109.6},0).wait(1).to({x:263.5,y:130.5},0).wait(1).to({x:292.3,y:151.4},0).wait(1).to({x:321.1,y:172.2},0).wait(1).to({x:349.9,y:193.1},0).wait(1).to({x:378.7,y:213.9},0).wait(1).to({x:407.5,y:234.8},0).wait(1).to({x:436.4,y:255.6},0).wait(1).to({x:465.2,y:276.5},0).wait(1).to({x:494,y:297.4},0).wait(1).to({x:522.8,y:318.2},0).wait(1).to({x:551.6,y:339.1},0).wait(1).to({x:580.4,y:360},0).wait(1).to({x:609.3,y:380.8},0).wait(1).to({x:638.1,y:401.7},0).wait(1).to({x:666.9,y:422.6},0).wait(1).to({x:695.7,y:443.4},0).wait(1).to({x:724.5,y:464.3},0).wait(1).to({x:753.3,y:485.1},0).wait(1).to({x:782.2,y:506},0).wait(1).to({x:811,y:526.9},0).wait(1).to({x:839.8,y:547.7},0).wait(1).to({x:868.6,y:568.6},0).wait(1).to({x:897.4,y:589.5},0).wait(1).to({x:926.3,y:610.3},0).wait(1).to({x:955.1,y:631.2},0).wait(1).to({x:983.9,y:652.1},0).wait(1).to({x:1012.7,y:672.9},0).wait(1).to({x:1041.5,y:693.8},0).wait(1).to({x:1070.4,y:714.7},0).wait(1));

	// Capa 7
	this.instance_2 = new lib.Símbolo3();
	this.instance_2.setTransform(-632.9,-401.7,1,1,0,0,0,1410.8,1081.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).wait(1).to({x:-584.3,y:-367},0).wait(1).to({x:-535.7,y:-332.4},0).wait(1).to({x:-487.2,y:-297.7},0).wait(1).to({x:-438.6,y:-263},0).wait(1).to({x:-390,y:-228.4},0).wait(1).to({x:-341.4,y:-193.7},0).wait(1).to({x:-292.9,y:-159.1},0).wait(1).to({x:-244.3,y:-124.4},0).wait(1).to({x:-195.7,y:-89.7},0).wait(1).to({x:-147.1,y:-55.1},0).wait(1).to({x:-98.5,y:-20.4},0).wait(1).to({x:-50,y:14.3},0).wait(1).to({x:-1.4,y:48.9},0).wait(1).to({x:47.1,y:83.5},0).wait(1).to({x:95.8,y:118.2},0).wait(1).to({x:144.3,y:152.9},0).wait(1).to({x:192.9,y:187.6},0).wait(1).to({x:241.5,y:222.2},0).wait(1).to({x:290.1,y:256.9},0).wait(1).to({x:338.7,y:291.6},0).wait(1).to({x:387.2,y:326.2},0).wait(1).to({x:435.8,y:360.9},0).wait(1).to({x:484.4,y:395.5},0).wait(1).to({x:533,y:430.2},0).wait(1).to({x:581.5,y:464.9},0).wait(1).to({x:630.1,y:499.5},0).wait(1).to({x:678.7,y:534.2},0).wait(1));

	// Capa 1
	this.instance_3 = new lib.Símbolo4();
	this.instance_3.setTransform(2431.9,1549.4,1,1,0,0,0,1410.8,1081.7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).wait(1).to({regY:1081.6,x:2389.4,y:1522.1},0).wait(1).to({x:2347,y:1494.9},0).wait(1).to({x:2304.6,y:1467.8},0).wait(1).to({x:2262.1,y:1440.6},0).wait(1).to({x:2219.7,y:1413.5},0).wait(1).to({x:2177.3,y:1386.3},0).wait(1).to({x:2134.9,y:1359.2},0).wait(1).to({x:2092.4,y:1332},0).wait(1).to({x:2050,y:1304.9},0).wait(1).to({x:2007.5,y:1277.7},0).wait(1).to({x:1965.1,y:1250.6},0).wait(1).to({x:1922.7,y:1223.4},0).wait(1).to({x:1880.2,y:1196.3},0).wait(1).to({x:1837.9,y:1169.2},0).wait(1).to({x:1795.4,y:1142},0).wait(1).to({x:1752.9,y:1114.8},0).wait(1).to({x:1710.5,y:1087.7},0).wait(1).to({x:1668.1,y:1060.6},0).wait(1).to({x:1625.7,y:1033.4},0).wait(1).to({x:1583.2,y:1006.3},0).wait(1).to({x:1540.8,y:979.1},0).wait(1).to({x:1498.4,y:952},0).wait(1).to({x:1455.9,y:924.8},0).wait(1).to({x:1413.5,y:897.7},0).wait(1).to({x:1371.1,y:870.5},0).wait(1).to({x:1328.7,y:843.4},0).wait(1).to({x:1286.2,y:816.2},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-248.6,-214.9,2403,1727.8);


(lib.scene01_drag_slider = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.instance = new lib.scene01_drag_slider_grafico("synched",0);
	this.instance.setTransform(79,18.9,1,1,0,0,0,79,18.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(51));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.9,-1,161.9,39.7);


(lib.scene01_drag_anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 3
	this.instance = new lib.Interpolación13("synched",0);
	this.instance.setTransform(79.1,18.9,0.626,0.308);
	this.instance._off = true;

	this.instance_1 = new lib.Interpolación14("synched",0);
	this.instance_1.setTransform(79.1,18.9,1.29,1.29);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},6).to({state:[{t:this.instance_1}]},14).wait(10));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({_off:true,scaleX:1.29,scaleY:1.29,alpha:0},14).wait(10));

	// Capa 2
	this.instance_2 = new lib.Interpolación13("synched",0);
	this.instance_2.setTransform(79.1,18.9,0.626,0.308);

	this.instance_3 = new lib.Interpolación14("synched",0);
	this.instance_3.setTransform(79.1,18.9,1.303,1.303);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},14).to({state:[]},1).wait(15));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true,scaleX:1.3,scaleY:1.3,alpha:0},14).wait(16));

	// Capa 1
	this.instance_4 = new lib.Interpolación15("synched",0);
	this.instance_4.setTransform(79.1,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:0.199},14).wait(1).to({startPosition:0},0).to({alpha:1},14).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(28.6,12.1,101,13.6);


(lib.scene01_drag = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.instance = new lib.scene01_drag_anim();
	this.instance.setTransform(78,78.1,1,1,0,0,0,76,18.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").p("AMWAAQAAA6gMASQgZAohlAaQizAunZAAQnYAAizguQhlgagZgoQgMgSAAg6QAAg6AMgSQAZgnBlgaQCzguHYAAQHZAACzAuQBlAaAZAnQAMASAAA6g");
	this.shape.setTransform(81,78.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1.2).p("AHvAAQAAAagIAIQgQARg/AMQhwAUkoAAQknAAhwgUQg/gMgQgRQgHgIAAgaQAAgYAHgJQAQgSA/gKQBwgVEnAAQEoAABwAVQA/AKAQASQAIAJAAAYg");
	this.shape_1.setTransform(80.9,78.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(11,114,181,0.6)").s().p("AmXA/Qg/gLgQgSQgIgIAAgaQAAgYAIgJQAQgRA/gLQBwgVEnAAQEoAABwAVQA/ALAQARQAIAJgBAYQABAagIAIQgQASg/ALQhwAUkoAAQknAAhwgUg");
	this.shape_2.setTransform(80.9,78.1);

	this.instance_1 = new lib.scene01_drag_slider();
	this.instance_1.setTransform(80.9,78.3,1,1,0,0,0,79,18.9);

	this.instance_2 = new lib.Interpolación19("synched",0);
	this.instance_2.setTransform(78.1,78.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(28.5,72,105.2,12.2);


(lib.scene01_destino = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{inicio:0,"play":101});

	// timeline functions:
	this.frame_100 = function() {
		this.gotoAndPlay("inicio");
	}
	this.frame_254 = function() {
		this.gotoAndPlay("inicio");
        
        this.parent.gotoAndPlay("inicio");
        jQuery(document).trigger("estadoInicial",[this]);
                //alert("hola");
                //
			jQuery(document).on("final",function(event){                
                
                this.parent.gotoAndStop("transicion");
                
                
            }.bind(this));
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(100).call(this.frame_100).wait(154).call(this.frame_254).wait(1));

	// Capa 3
	this.instance = new lib.Interpolación25("synched",0);
	this.instance.setTransform(24.4,24.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:-7.2},0).wait(1).to({rotation:-14.4},0).wait(1).to({rotation:-21.6},0).wait(1).to({rotation:-28.8},0).wait(1).to({rotation:-35.9},0).wait(1).to({rotation:-43.1},0).wait(1).to({rotation:-50.3},0).wait(1).to({rotation:-57.5},0).wait(1).to({rotation:-64.7},0).wait(1).to({rotation:-71.9},0).wait(1).to({rotation:-79.1},0).wait(1).to({rotation:-86.3},0).wait(1).to({rotation:-93.5},0).wait(1).to({rotation:-100.7},0).wait(1).to({rotation:-107.8},0).wait(1).to({rotation:-115},0).wait(1).to({rotation:-122.2},0).wait(1).to({rotation:-129.4},0).wait(1).to({rotation:-136.6},0).wait(1).to({rotation:-143.8},0).wait(1).to({rotation:-151},0).wait(1).to({rotation:-158.2},0).wait(1).to({rotation:-165.4},0).wait(1).to({rotation:-172.6},0).wait(1).to({rotation:-179.7},0).wait(1).to({rotation:-186.9},0).wait(1).to({rotation:-194.1},0).wait(1).to({rotation:-201.3},0).wait(1).to({rotation:-208.5},0).wait(1).to({rotation:-215.7},0).wait(1).to({rotation:-222.9},0).wait(1).to({rotation:-230.1},0).wait(1).to({rotation:-237.3},0).wait(1).to({rotation:-244.5},0).wait(1).to({rotation:-251.6},0).wait(1).to({rotation:-258.8},0).wait(1).to({rotation:-266},0).wait(1).to({rotation:-273.2},0).wait(1).to({rotation:-280.4},0).wait(1).to({rotation:-287.6},0).wait(1).to({rotation:-294.8},0).wait(1).to({rotation:-302},0).wait(1).to({rotation:-309.2},0).wait(1).to({rotation:-316.4},0).wait(1).to({rotation:-323.5},0).wait(1).to({rotation:-330.7},0).wait(1).to({rotation:-337.9},0).wait(1).to({rotation:-345.1},0).wait(1).to({rotation:-352.3},0).wait(1).to({rotation:-359.5},0).wait(1).to({rotation:-366.7},0).wait(1).to({rotation:-373.9},0).wait(1).to({rotation:-381.1},0).wait(1).to({rotation:-388.3},0).wait(1).to({rotation:-395.4},0).wait(1).to({rotation:-402.6},0).wait(1).to({rotation:-409.8},0).wait(1).to({rotation:-417},0).wait(1).to({rotation:-424.2},0).wait(1).to({rotation:-431.4},0).wait(1).to({rotation:-438.6},0).wait(1).to({rotation:-445.8},0).wait(1).to({rotation:-453},0).wait(1).to({rotation:-460.2},0).wait(1).to({rotation:-467.3},0).wait(1).to({rotation:-474.5},0).wait(1).to({rotation:-481.7},0).wait(1).to({rotation:-488.9},0).wait(1).to({rotation:-496.1},0).wait(1).to({rotation:-503.3},0).wait(1).to({rotation:-510.5},0).wait(1).to({rotation:-517.7},0).wait(1).to({rotation:-524.9},0).wait(1).to({rotation:-532.1},0).wait(1).to({rotation:-539.2},0).wait(1).to({rotation:-546.4},0).wait(1).to({rotation:-553.6},0).wait(1).to({rotation:-560.8},0).wait(1).to({rotation:-568},0).wait(1).to({rotation:-575.2},0).wait(1).to({rotation:-582.4},0).wait(1).to({rotation:-589.6},0).wait(1).to({rotation:-596.8},0).wait(1).to({rotation:-604},0).wait(1).to({rotation:-611.1},0).wait(1).to({rotation:-618.3},0).wait(1).to({rotation:-625.5},0).wait(1).to({rotation:-632.7},0).wait(1).to({rotation:-639.9},0).wait(1).to({rotation:-647.1},0).wait(1).to({rotation:-654.3},0).wait(1).to({rotation:-661.5},0).wait(1).to({rotation:-668.7},0).wait(1).to({rotation:-675.9},0).wait(1).to({rotation:-683},0).wait(1).to({rotation:-690.2},0).wait(1).to({rotation:-697.4},0).wait(1).to({rotation:-704.6},0).wait(1).to({rotation:-711.8},0).wait(1).to({rotation:-719},0).to({_off:true},1).wait(154));

	// Capa 1
	this.instance_1 = new lib.Interpolación21("synched",0);
	this.instance_1.setTransform(24.4,24.4);
	this.instance_1._off = true;

	this.instance_2 = new lib.Interpolación22("synched",0);
	this.instance_2.setTransform(24.4,24.4,2.15,2.15);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},101).to({state:[{t:this.instance_2}]},33).wait(121));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(101).to({_off:false},0).to({_off:true,scaleX:2.15,scaleY:2.15,alpha:0},33).wait(121));

	// Capa 1 copia
	this.instance_3 = new lib.Interpolación23("synched",0);
	this.instance_3.setTransform(24.4,24.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(101).to({_off:false},0).to({startPosition:0},33).wait(75).to({startPosition:0},0).to({startPosition:0},45).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,50.7,50.7);


// stage content:



(lib.scene01_slider_v04_trazado = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{destino:242,transicion:243,"inicio":1});

	// timeline functions:
	this.frame_0 = function() {
		//transicion con texto de inicio scene01
		
		this.stop();
	}
	this.frame_1 = function() {
		//codigo de slider "inicio"
		
		this.stop();
					
					this.scene01_destino.play();
					
		
		var dragger = this.scene01_drag;
		var destino = this.scene01_destino;
		var origen = Math.round(dragger.x);
		this.ready = false;
		this.posicion = 0;
		dragger.addEventListener("mousedown", fl_Click.bind(this));
		
		
		function fl_Click()
		{
		/* Código para obtener el número del fotograma actual
		*/
		
					//var frameNumber = this.scene01_texto.currentFrame;
					//frameNumber = frameNumber - 1;
								
					//this.scene01_texto.gotoAndStop(frameNumber);	
			
		}
		
		dragger.on("pressmove",function(e){
			
				var aux = Math.round((  e.stageX - origen )*100 / (destino.x - origen));
				var proporcionX;
				var posicionX;
			
			if (aux < 0)
				proporcionX = 0
			else if (aux > 100)
				proporcionX = 100
			else 
				proporcionX = aux;
			
			if(proporcionX != 0)
			{		
				this.gotoAndStop(proporcionX+38);
			}
			
			this.proporcion = proporcionX;
				console.log(aux);
				//console.log("origen x: "+dragger.x+" origen y: " +dragger.y);
			
			
			
			
		}.bind(this));
		
		 dragger.on("pressup",function(e){
		 
			 
			 if ((this.proporcion < 100) && (this.proporcion > 0)){					
				 		
				 this.gotoAndPlay(240-this.proporcion);
				 
				 
			 }		
             
              if ((this.proporcion == 100))
			 {
				 
					destino.gotoAndPlay("play");
					this.gotoAndStop("destino");
					
              }
			 
		}.bind(this));
        
        
        jQuery(document).on("posicionMaxima",function(event,that,contador){
            
                    this.scene01_destino.gotoAndPlay("play");
					this.gotoAndStop("destino");
            
        }.bind(this));        
	 
    }
	this.frame_241 = function() {
		//regresar a etiquita inicio cuando vuelve slider
		this.gotoAndStop("inicio");
	}
	this.frame_242 = function() {
		//etiqueta "destino" (desaparece boton slider)
		jQuery(document).trigger("pressUp",[this]);
		this.stop();
	}
	this.frame_243 = function() {
		//transicion final "transicion"
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(240).call(this.frame_241).wait(1).call(this.frame_242).wait(1).call(this.frame_243).wait(1));

	// transicion
	this.transicion = new lib.transicion_nubes_on();
	this.transicion.setTransform(960,600,1,1,0,0,0,960,600);

	this.transicion_1 = new lib.transicion_nubes_off();
	this.transicion_1.setTransform(960,600,1,1,0,0,0,960,600);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.transicion}]}).to({state:[]},1).to({state:[{t:this.transicion_1}]},242).wait(1));

	// boton
	this.scene01_drag = new lib.scene01_drag();
	this.scene01_drag.setTransform(778.8,860.6,0.802,0.802,-34.1,0,0,78,78.1);
	new cjs.ButtonHelper(this.scene01_drag, 0, 1, 2, false, new lib.scene01_drag(), 3);

	this.timeline.addTween(cjs.Tween.get(this.scene01_drag).wait(38).to({regX:78.4,regY:78.7,scaleX:0.79,scaleY:0.79,x:778.9,y:860.4},0).wait(1).to({regX:81,regY:78,scaleX:0.8,scaleY:0.8,rotation:-33.8,x:787.8,y:853.9},0).wait(1).to({rotation:-33.6,x:795.3,y:849.2},0).wait(1).to({rotation:-33.3,x:802.8,y:844.5},0).wait(1).to({rotation:-33.1,x:810.4,y:839.9},0).wait(1).to({rotation:-32.9,x:818,y:835.3},0).wait(1).to({rotation:-32.6,x:825.6,y:830.8},0).wait(1).to({rotation:-32.4,x:833.2,y:826.3},0).wait(1).to({rotation:-32.2,x:840.9,y:821.9},0).wait(1).to({rotation:-31.9,x:848.7,y:817.5},0).wait(1).to({rotation:-31.7,x:856.4,y:813.2},0).wait(1).to({rotation:-31.4,x:864.2,y:808.9},0).wait(1).to({rotation:-31.2,x:872,y:804.7},0).wait(1).to({rotation:-31,x:879.8,y:800.5},0).wait(1).to({rotation:-30.7,x:887.6,y:796.3},0).wait(1).to({rotation:-30.5,x:895.5,y:792.2},0).wait(1).to({rotation:-30.3,x:903.4,y:788.1},0).wait(1).to({rotation:-30,x:911.3,y:784.1},0).wait(1).to({rotation:-29.8,x:919.2,y:780.2},0).wait(1).to({rotation:-29.5,x:927.2,y:776.2},0).wait(1).to({rotation:-29.3,x:935.2,y:772.4},0).wait(1).to({rotation:-29.1,x:943.2,y:768.5},0).wait(1).to({rotation:-28.8,x:951.2,y:764.7},0).wait(1).to({rotation:-28.6,x:959.2,y:761},0).wait(1).to({rotation:-28.4,x:967.2,y:757.2},0).wait(1).to({rotation:-28.1,x:975.4,y:753.6},0).wait(1).to({rotation:-27.9,x:983.4,y:749.9},0).wait(1).to({rotation:-27.6,x:991.5,y:746.4},0).wait(1).to({rotation:-27.4,x:999.7,y:742.7},0).wait(1).to({rotation:-27.2,x:1007.8,y:739.3},0).wait(1).to({rotation:-26.9,x:1016,y:735.8},0).wait(1).to({rotation:-26.7,x:1024.2,y:732.3},0).wait(1).to({rotation:-26.5,x:1032.3,y:728.9},0).wait(1).to({rotation:-26.2,x:1040.5,y:725.5},0).wait(1).to({rotation:-26,x:1048.8,y:722.2},0).wait(1).to({rotation:-25.7,x:1057,y:718.9},0).wait(1).to({rotation:-25.5,x:1065.2,y:715.6},0).wait(1).to({rotation:-25.3,x:1073.5,y:712.4},0).wait(1).to({rotation:-25,x:1081.8,y:709.2},0).wait(1).to({rotation:-24.8,x:1090,y:706},0).wait(1).to({rotation:-24.6,x:1098.3,y:702.9},0).wait(1).to({rotation:-24.3,x:1106.7,y:699.8},0).wait(1).to({rotation:-24.1,x:1115,y:696.7},0).wait(1).to({rotation:-23.8,x:1123.3,y:693.7},0).wait(1).to({rotation:-23.6,x:1131.7,y:690.7},0).wait(1).to({rotation:-23.4,x:1140,y:687.7},0).wait(1).to({rotation:-23.1,x:1148.4,y:684.8},0).wait(1).to({rotation:-22.9,x:1156.7,y:681.9},0).wait(1).to({rotation:-22.7,x:1165.2,y:679},0).wait(1).to({rotation:-22.4,x:1173.6,y:676.1},0).wait(1).to({rotation:-22.2,x:1182,y:673.3},0).wait(1).to({rotation:-21.9,x:1190.4,y:670.5},0).wait(1).to({rotation:-21.7,x:1198.9,y:667.7},0).wait(1).to({rotation:-21.5,x:1207.3,y:665},0).wait(1).to({rotation:-21.2,x:1215.7,y:662.3},0).wait(1).to({rotation:-21,x:1224.2,y:659.6},0).wait(1).to({rotation:-20.7,x:1232.6,y:657},0).wait(1).to({rotation:-20.5,x:1241.1,y:654.4},0).wait(1).to({rotation:-20.3,x:1249.6,y:651.8},0).wait(1).to({rotation:-20,x:1258.1,y:649.2},0).wait(1).to({rotation:-19.8,x:1266.6,y:646.7},0).wait(1).to({rotation:-19.6,x:1275.1,y:644.2},0).wait(1).to({rotation:-19.3,x:1283.6,y:641.6},0).wait(1).to({rotation:-19.1,x:1292.2,y:639.2},0).wait(1).to({rotation:-18.8,x:1300.7,y:636.8},0).wait(1).to({rotation:-18.6,x:1309.2,y:634.3},0).wait(1).to({rotation:-18.4,x:1317.8,y:631.9},0).wait(1).to({rotation:-18.1,x:1326.3,y:629.6},0).wait(1).to({rotation:-17.9,x:1334.8,y:627.2},0).wait(1).to({rotation:-17.7,x:1343.4,y:624.9},0).wait(1).to({rotation:-17.4,x:1352,y:622.6},0).wait(1).to({rotation:-17.2,x:1360.5,y:620.4},0).wait(1).to({rotation:-16.9,x:1369.2,y:618.1},0).wait(1).to({rotation:-16.7,x:1377.8,y:615.9},0).wait(1).to({rotation:-16.5,x:1386.4,y:613.7},0).wait(1).to({rotation:-16.2,x:1394.9,y:611.6},0).wait(1).to({rotation:-16,x:1403.6,y:609.4},0).wait(1).to({rotation:-15.8,x:1412.2,y:607.3},0).wait(1).to({rotation:-15.5,x:1420.8,y:605.1},0).wait(1).to({rotation:-15.3,x:1429.4,y:603.1},0).wait(1).to({rotation:-15,x:1438.1,y:601},0).wait(1).to({rotation:-14.8,x:1446.7,y:598.9},0).wait(1).to({rotation:-14.6,x:1455.3,y:596.9},0).wait(1).to({rotation:-14.3,x:1464,y:594.9},0).wait(1).to({rotation:-14.1,x:1472.6,y:592.9},0).wait(1).to({rotation:-13.9,x:1481.2,y:591},0).wait(1).to({rotation:-13.6,x:1489.9,y:589},0).wait(1).to({rotation:-13.4,x:1498.6,y:587.1},0).wait(1).to({rotation:-13.1,x:1507.2,y:585.2},0).wait(1).to({rotation:-12.9,x:1515.9,y:583.3},0).wait(1).to({rotation:-12.7,x:1524.5,y:581.5},0).wait(1).to({rotation:-12.4,x:1533.3,y:579.6},0).wait(1).to({rotation:-12.2,x:1541.9,y:577.8},0).wait(1).to({rotation:-12,x:1550.6,y:576},0).wait(1).to({rotation:-11.7,x:1559.3,y:574.1},0).wait(1).to({rotation:-11.5,x:1568,y:572.5},0).wait(1).to({rotation:-11.2,x:1576.7,y:570.7},0).wait(1).to({rotation:-11,x:1585.4,y:569},0).wait(1).to({rotation:-10.8,x:1594.1,y:567.2},0).wait(1).to({rotation:-10.5,x:1602.8,y:565.5},0).wait(1).to({rotation:-10.3,x:1611.5,y:563.8},0).wait(1).to({rotation:-10.1,x:1620.3,y:562.2},0).wait(1).to({regX:77.5,regY:77.5,scaleX:0.79,rotation:-10,x:1618.3,y:563.2},0).wait(1).to({regX:81,regY:78,scaleX:0.8,rotation:-10.3,x:1612.4,y:564.7},0).wait(1).to({rotation:-10.5,x:1603.7,y:566.4},0).wait(1).to({rotation:-10.8,x:1595,y:568},0).wait(1).to({rotation:-11,x:1586.3,y:569.8},0).wait(1).to({rotation:-11.2,x:1577.6,y:571.5},0).wait(1).to({rotation:-11.5,x:1568.9,y:573.3},0).wait(1).to({rotation:-11.7,x:1560.2,y:575},0).wait(1).to({rotation:-12,x:1551.5,y:576.8},0).wait(1).to({rotation:-12.2,x:1542.8,y:578.6},0).wait(1).to({rotation:-12.4,x:1534.1,y:580.4},0).wait(1).to({rotation:-12.7,x:1525.4,y:582.3},0).wait(1).to({rotation:-12.9,x:1516.8,y:584.1},0).wait(1).to({rotation:-13.1,x:1508.1,y:586},0).wait(1).to({rotation:-13.4,x:1499.5,y:587.9},0).wait(1).to({rotation:-13.6,x:1490.8,y:589.8},0).wait(1).to({rotation:-13.9,x:1482.1,y:591.8},0).wait(1).to({rotation:-14.1,x:1473.5,y:593.7},0).wait(1).to({rotation:-14.3,x:1464.9,y:595.7},0).wait(1).to({rotation:-14.6,x:1456.2,y:597.7},0).wait(1).to({rotation:-14.8,x:1447.6,y:599.7},0).wait(1).to({rotation:-15,x:1439,y:601.8},0).wait(1).to({rotation:-15.3,x:1430.3,y:603.8},0).wait(1).to({rotation:-15.5,x:1421.7,y:605.9},0).wait(1).to({rotation:-15.8,x:1413.1,y:608},0).wait(1).to({rotation:-16,x:1404.5,y:610.1},0).wait(1).to({rotation:-16.2,x:1395.9,y:612.3},0).wait(1).to({rotation:-16.5,x:1387.3,y:614.5},0).wait(1).to({rotation:-16.7,x:1378.7,y:616.7},0).wait(1).to({rotation:-16.9,x:1370.1,y:618.9},0).wait(1).to({rotation:-17.2,x:1361.5,y:621.2},0).wait(1).to({rotation:-17.4,x:1352.9,y:623.4},0).wait(1).to({rotation:-17.7,x:1344.4,y:625.7},0).wait(1).to({rotation:-17.9,x:1335.8,y:628},0).wait(1).to({rotation:-18.1,x:1327.3,y:630.3},0).wait(1).to({rotation:-18.4,x:1318.7,y:632.7},0).wait(1).to({rotation:-18.6,x:1310.2,y:635},0).wait(1).to({rotation:-18.8,x:1301.7,y:637.5},0).wait(1).to({rotation:-19.1,x:1293.1,y:639.9},0).wait(1).to({rotation:-19.3,x:1284.6,y:642.4},0).wait(1).to({rotation:-19.6,x:1276,y:644.9},0).wait(1).to({rotation:-19.8,x:1267.6,y:647.4},0).wait(1).to({rotation:-20,x:1259.1,y:649.9},0).wait(1).to({rotation:-20.3,x:1250.6,y:652.5},0).wait(1).to({rotation:-20.5,x:1242.1,y:655.1},0).wait(1).to({rotation:-20.7,x:1233.6,y:657.7},0).wait(1).to({rotation:-21,x:1225.1,y:660.3},0).wait(1).to({rotation:-21.2,x:1216.7,y:663},0).wait(1).to({rotation:-21.5,x:1208.3,y:665.7},0).wait(1).to({rotation:-21.7,x:1199.9,y:668.4},0).wait(1).to({rotation:-21.9,x:1191.4,y:671.2},0).wait(1).to({rotation:-22.2,x:1183,y:674},0).wait(1).to({rotation:-22.4,x:1174.6,y:676.8},0).wait(1).to({rotation:-22.7,x:1166.2,y:679.6},0).wait(1).to({rotation:-22.9,x:1157.7,y:682.5},0).wait(1).to({rotation:-23.1,x:1149.4,y:685.4},0).wait(1).to({rotation:-23.4,x:1141,y:688.3},0).wait(1).to({rotation:-23.6,x:1132.7,y:691.3},0).wait(1).to({rotation:-23.8,x:1124.3,y:694.4},0).wait(1).to({rotation:-24.1,x:1116,y:697.3},0).wait(1).to({rotation:-24.3,x:1107.7,y:700.4},0).wait(1).to({rotation:-24.6,x:1099.3,y:703.5},0).wait(1).to({rotation:-24.8,x:1091.1,y:706.6},0).wait(1).to({rotation:-25,x:1082.8,y:709.8},0).wait(1).to({rotation:-25.3,x:1074.5,y:713},0).wait(1).to({rotation:-25.5,x:1066.2,y:716.2},0).wait(1).to({rotation:-25.7,x:1058,y:719.5},0).wait(1).to({rotation:-26,x:1049.8,y:722.8},0).wait(1).to({rotation:-26.2,x:1041.5,y:726.1},0).wait(1).to({rotation:-26.5,x:1033.4,y:729.4},0).wait(1).to({rotation:-26.7,x:1025.2,y:732.9},0).wait(1).to({rotation:-26.9,x:1017,y:736.3},0).wait(1).to({rotation:-27.2,x:1008.8,y:739.8},0).wait(1).to({rotation:-27.4,x:1000.7,y:743.3},0).wait(1).to({rotation:-27.6,x:992.6,y:746.9},0).wait(1).to({rotation:-27.9,x:984.5,y:750.5},0).wait(1).to({rotation:-28.1,x:976.4,y:754.1},0).wait(1).to({rotation:-28.4,x:968.3,y:757.8},0).wait(1).to({rotation:-28.6,x:960.3,y:761.5},0).wait(1).to({rotation:-28.8,x:952.2,y:765.3},0).wait(1).to({rotation:-29.1,x:944.3,y:769},0).wait(1).to({rotation:-29.3,x:936.2,y:772.9},0).wait(1).to({rotation:-29.5,x:928.3,y:776.8},0).wait(1).to({rotation:-29.8,x:920.3,y:780.7},0).wait(1).to({rotation:-30,x:912.3,y:784.7},0).wait(1).to({rotation:-30.3,x:904.4,y:788.6},0).wait(1).to({rotation:-30.5,x:896.6,y:792.7},0).wait(1).to({rotation:-30.7,x:888.7,y:796.8},0).wait(1).to({rotation:-31,x:880.8,y:801},0).wait(1).to({rotation:-31.2,x:873,y:805.2},0).wait(1).to({rotation:-31.4,x:865.3,y:809.4},0).wait(1).to({rotation:-31.7,x:857.5,y:813.7},0).wait(1).to({rotation:-31.9,x:849.8,y:818},0).wait(1).to({rotation:-32.2,x:842,y:822.4},0).wait(1).to({rotation:-32.4,x:834.3,y:826.8},0).wait(1).to({rotation:-32.6,x:826.7,y:831.3},0).wait(1).to({rotation:-32.9,x:819.1,y:835.8},0).wait(1).to({rotation:-33.1,x:811.5,y:840.4},0).wait(1).to({rotation:-33.3,x:803.9,y:845},0).wait(1).to({rotation:-33.6,x:796.4,y:849.6},0).wait(1).to({rotation:-33.8,x:788.9,y:854.3},0).wait(1).to({rotation:-34.1,x:781.4,y:859.2},0).to({_off:true},1).wait(2));

	// linea_guia
	this.scene01_destino = new lib.scene01_destino();
	this.scene01_destino.setTransform(1618.6,563.4,1.106,1.106,0,0,0,24.5,24.6);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.6)").s().p("EhBqAXTQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBIAxgiQABAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgyAiIgDABIgBAAgEhAHAWPQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAYgQIAbgRQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgaASIgYAQIgDAAIgBAAgEg+iAVNQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAzggQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgzAgIgDABIgBAAgEg88AUNQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIAzggQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABIgzAfIgCABIgCAAgEg7VATOQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAygeQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAQAAAAgBABIgyAeIgCAAIgCAAgEg5rASQQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIA0geQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAABIg0AeIgCAAIgCAAgEg4CARUQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAIA1geQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAABIg1AeIgCAAIgBAAgEg2aAQZQAAAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIA1gdQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIg1AdIgCAAIgCAAgEg0wAPfQAAAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIA1gdQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIg1AdIgCAAIgCAAgEgzGAOmQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIA1gcQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAIg2AcIgCAAIgCAAgEgxbANuQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIA1gcQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAIg2AcIgCAAIgCAAgEgvwAM2QAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIA1gbQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAIg2AbIgCAAIgCAAgEguEAMAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA2gbQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAIg2AbIgCAAIgCAAgEgsYALKQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA2gbQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAIg2AbIgCAAIgCAAgEgqsAKVQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIA2gaQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIg3AaIgCAAIgCAAgEgo/AJhQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA2gaQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIg2AaIgDAAIgBAAgEgnTAItQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA2gZQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIg2AZIgCAAIgCAAgEglmAH7QAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA2gZQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIg2AZIgCAAIgCAAgEgj5AHJQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA4gZQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIg4AZIgCAAIgCAAgEgiIAGXQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA3gYQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIg3AYIgCAAIgBAAgEggaAFnQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA3gYQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIg3AYIgCAAIgBAAgA+sE3QgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA3gYQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIg3AYIgCAAIgBAAgA8+EIQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIA3gXQAAAAABgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIg3AXIgCAAIgCAAgA7QDaQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAIA4gXQAAAAABgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIg4AXIgCAAIgCAAgA5hCsQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAIA4gXQAAAAABgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIg4AXIgCAAIgCAAgA3xB+QgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIA4gWQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABIg4AWIgCAAIgCgBgA2BBSQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIA4gWQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABIg4AWIgCAAIgCgBgA0RAmQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA4gWQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABIg4AWIgCAAIgCgBgAyhgEQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA4gVQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABIg4AVIgCAAIgCgBgAwxguQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA5gVQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIg4AVIgCAAIgCgBgAvAhYQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIA5gVQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIg4AVIgCAAIgCgBgAtPiCQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIA5gVQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIg4AVIgCAAIgCgBgAreirQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIA5gUQABgBAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIg5AUIgCAAIgCAAgApsjTQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIA5gUQAAgBABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIg4AUIgCAAIgCAAgAn7j7QAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIA5gUQAAgBABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIg5AUIgBAAIgDAAgAmJkjQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIA5gUQAAgBABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIg5AUIgBAAIgDAAgAkXlLQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA5gTQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAABIg5ATIgCAAIgCgBgAiklxQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA5gTQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABIg5ATIgBAAIgCgBgAgymXQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA4gTQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAABIg4ATIgBAAIgCgBgAA+m9QAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA6gTQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQABABgBAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAABIg6ATIgCAAIgCgBgACxniQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABAAIA4gSQABgBAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIg4ASIgCAAIgCAAgAEkoHQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIA5gSQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABIg5ASIgBAAIgCgBgAGZosQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAIAQgFIAqgNQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABIgqANIgQAFIgBAAIgCgBgAIMpQQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAIA5gRQABgBABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIg5ASIgCAAIgCgBgAJ/pyQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABAAIA6gRQAAgBABAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQABAAgBABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAAAIg6ARIgCAAIgCAAgALzqUQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABAAIA5gRQABgBABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIg5ARIgCAAIgCAAgANmq2QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAAAAAIA6gRQABgBAAAAQABAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIg6ARIgBAAIgDAAgAParYQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAAAAAIA6gRQABgBAAAAQABAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIg6ARIgBAAIgDAAgAROr6QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gQQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6AQIgBAAIgDgBgATCsaQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gQQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6AQIgBAAIgDgBgAU2s6QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gQQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6AQIgBAAIgDgBgAWqtaQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gQQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6AQIgBAAIgDgBgAYet6QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gQQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6AQIgBAAIgDgBgAaSuZQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gPQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6APIgBAAIgDgBgAcGu3QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gPQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6APIgBAAIgDgBgAd6vVQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gPQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBABIg6APIgBAAIgDgBgAfuvzQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAIA6gPQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABIg7APIgBAAIgDgBgEAhjgQQQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIA6gOQABgBAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIg6AOIgCAAIgCAAgEAjXgQsQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIA6gOQABgBAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIg7AOIgBAAIgDAAgEAlMgRIQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIA7gOQAAgBABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIg7AOIgBAAIgDAAgEAnCgRkQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIA7gOQAAgBABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIg7AOIgBAAIgDAAgEAo4gSAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIA7gOQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIg7ANIgBAAIgDAAgEAqugSbQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAIA7gNQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIg7ANIgBAAIgDgBgEAskgS1QAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAIA7gNQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIg7ANIgBAAIgDgBgEAuagTPQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAIA7gNQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIg7ANIgBAAIgDgBgEAwQgTpQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAIA7gNQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIg7ANIgBAAIgDgBgEAyGgUCQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEAz8gUaQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEA1ygUyQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEA3ogVKQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEA5egViQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEA7UgV6QAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAIA7gMQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIg7AMIgBAAIgDAAgEA9KgWSQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIA6gLQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQgBAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIg6ALIgBAAIgDgBgEA/AgWpQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIA8gMQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIg8AMIgBAAIgCgBgEBA4gXAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAvgJQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgvAJIgBAAIgCgBg");
	this.shape.setTransform(1198.1,711.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.scene01_destino}]}).wait(244));

	// boton_marca
	this.instance = new lib.scene01_drag_anim();
	this.instance.setTransform(779,860.6,0.805,0.805,-34.2,0,0,76,18.9);
	this.instance.alpha = 0.199;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXA1IAAhnIAKAAIABARIAAABQAFgJAHgGQAGgFALAAIAEAAIADABIgBALIgIgBQgLAAgFAGQgIAGgDALIAABHg");
	this.shape_1.setTransform(716.3,766.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AghAuQgIgIAAgOQAAgPAMgIQANgHASAAIAaAAIAAgNQAAgMgIgGQgGgGgOAAQgKAAgHAFQgHAGAAAJIgLAAIAAAAQgBgMALgJQALgJAPAAQARAAALAJQAKAIAAARIAAAyIABALIACAKIgMAAIgCgJIAAgJQgGAJgKAGQgKAFgKAAQgQAAgJgIgAgUAIQgJAGAAAKQAAAJAFAFQAHAGAKAAQAMAAAJgGQAKgHAEgKIAAgUIgaAAQgMAAgKAHg");
	this.shape_2.setTransform(706.8,767);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA1IAAhnIAKAAIABARIAAABQAFgJAHgGQAGgFALAAIAEAAIADABIgBALIgIgBQgLAAgFAGQgIAGgDALIAABHg");
	this.shape_3.setTransform(698.7,766.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBA8QgGgHAAgPIAAhDIgTAAIAAgKIATAAIAAgbIAJAAIAAAbIAYAAIAAAKIgYAAIAABDQAAAKAEAEQAEAFAGAAIAEgBIAFgBIACAJIgGACIgHABQgLAAgEgHg");
	this.shape_4.setTransform(691.3,765.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcAtQgLgJABgNIAAAAIALAAQABALAIAFQAJAFAKAAQAMAAAIgFQAHgGAAgIQAAgHgGgGQgGgFgQgEQgRgDgJgFQgJgHAAgMQAAgNAKgIQAKgIAPAAQASAAAKAJQALAJgBANIAAAAIgLAAQAAgJgHgGQgIgGgMAAQgLAAgGAFQgHAGAAAHQAAAHAGAFQAFAFAPADQATAFAJAFQAKAHAAANQAAANgLAIQgLAIgRAAQgSAAgLgJg");
	this.shape_5.setTransform(683.1,767);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AghAuQgIgIAAgOQAAgPANgIQAMgHARAAIAaAAIAAgNQAAgMgGgGQgIgGgNAAQgKAAgHAFQgIAGAAAJIgLAAIAAAAQAAgMAKgJQAMgJAPAAQARAAALAJQALAIAAARIAAAyIAAALIACAKIgMAAIgCgJIgBgJQgFAJgJAGQgLAFgLAAQgPAAgJgIgAgUAIQgJAGAAAKQAAAJAFAFQAHAGAKAAQALAAALgGQAJgHADgKIAAgUIgaAAQgMAAgJAHg");
	this.shape_6.setTransform(672.5,767);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXA1IAAhnIAKAAIABARIAAABQAFgJAHgGQAGgFALAAIAEAAIADABIgBALIgIgBQgLAAgFAGQgIAGgDALIAABHg");
	this.shape_7.setTransform(664.5,766.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgXA1IAAhnIAKAAIABARIAAABQAFgJAHgGQAGgFALAAIAEAAIADABIgBALIgIgBQgLAAgFAGQgIAGgDALIAABHg");
	this.shape_8.setTransform(657.6,766.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAtBGIgOgnIg9AAIgOAnIgMAAIA0iMIAJAAIA0CMgAgaAVIA1AAIgbhKIAAAAg");
	this.shape_9.setTransform(647.5,765.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("rgba(255,255,255,0.6)").ss(1,0,0,10,true).p("AkGllIINLL");
	this.shape_10.setTransform(742.7,810.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.instance}]}).wait(244));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-222.8,52.5,3879.9,2445.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;