(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1920,
	height: 1200,
	fps: 24,
	color: "#999999",
	manifest: []
};



// symbols:



(lib.Símbolo6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("Egp0AsKQjngkiniiQikiggujeQhWBHhqAeQhvAghygSQjVgih+ivQh/iuAijWQAViCBPhoQBMhlBzg2QhHhhgeh0Qgdh5AUh8QAoj6DNiVQDOiUD6AnQBvARBiA5QgYhkAQhrQAijVCuh8QCwh+DVAhQDVAjB+CtQB/CugiDVQgFAcgIAeQCHh+Cvg3QC1g5C9AeQFKA1DFEPQDEEPg0FLQg1FLkPDFQkQDElKg2QiQgWiAhIQArBhAOBoQAQBtgSBsQgxEwj4C1QjECNjlAAQg/AAhBgLgEApYAVXQh0g0gth2Qgth3AzhzQAWgyAogoQgoAGgogFQgpgFgmgRQhqgvgqhtQgphtAvhqQAlhRBLgtQBKgsBWAFQgSgmAAgqQgBgsASgoIAAgCQgviUBBiPQA1h3BwhCQBthCB+AHQgag4gBg+QgBg/Aag7QAxhuBxgrQBwgrBuAyQBDAdAsA6QArA4ANBFQA+gYBDAAQBFACBAAdQCBA5AzCEQAyCEg6CBQgZA5gtAtQA6AAA3AXQBuAxAqBwQArBxgxBuQgxBthwArQhxArhtgxIgdgPQAwBbAEBmQAFBpgsBhQhMCriuBCQiuBDiqhMQgZgMgXgNQgGAngRAlQgzB0h3AtQg3AVg3AAQg+AAg9gbgEAq3ghlQhGgggchHQgchIAghHQAfhGBIgbQAfgNAiAAQgUgOgPgTQgPgUgJgYQgZhCAchAQAdhBBCgZQAzgTA0ANQAzANAjAnQAJgZARgSQATgTAYgJQAvgSAtAUQAtAVASAuQALAcgEAeQgDAdgRAYQAZALATAUQAUAUALAbQAVA3gZA1QgXA1g3AVQgYAKgaAAQAQARAKAXQARAugUAuQgUAtgvARQguASgtgUQgugVgSgtIgDgOQgNApgdAfQgdAhgpAPQgiANghAAQgmAAglgRg");
	this.shape.setTransform(414.2,259.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-24,828.4,567.4);


(lib.Símbolo5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("A5ib1QhhgKhUguQhSgug7hJQg/BLhbAmQheAmhlgLQiogRhpiCQhqiDARimQAKhZAthNQAthJBGgyQidhQhXiaQhYifATi1QAYjtC6iXQC5iUDtAZQBWAIBOAhQBLAfBBAzQgdhtAMhwQAbkDDKikQDKikECAaQEDAcCkDJQCkDLgbECQgPCShPB8QhMB5h6BLQAYABAWACQCmARBqCCQBqCCgSCnQgRCniCBqQiCBpingRQhTgJhGgnQAXBVgKBXQgUDEiZB8QiEBrijAAQgbAAgbgDgAaBCsQhxhtgDibIAAgDQg2ADg5gPQiZgmhRiHQguhNgHhYQgHhWAghRIgXAPQhXA1higZQhjgYg0hXQg0hWAYhjQAZhiBWg1QAsgZAwgHQgqghgbgtQg9hmAch0QAdh0Bmg9QAzgeA5gIQA4gIA3AOQADg8AfgyQAfg1A1ggQBXg0BiAYQBjAZA0BXQAbAuAGA2QAGAzgQAyQBpgTBiAsQBkAsA5BeQAQAbALAcIAUAHQA0AWApAnQAhgyA0gdQA1geA9gBQBmgBBJBGQBJBGABBmQABA1gWAyQgVAvgmAjQBkAkA/BXQBBBZABBuQADCQhkBnQhkBoiQADQg0ABgxgOQgwgOgqgaQAZBAABBEQADCbhtByQhtBwieAEIgHAAQiYAAhvhrg");
	this.shape.setTransform(281.5,178.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,563,357);


(lib.Símbolo4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("EhbiCoIQvNjTolthQjFk0hjliQhilTgCllQkZGPmKEJQuIJqwmjkQwljmpWurQjklohtl/Qojh/k4nYQlBnpB2o8QB2o+HolAQC3h4DMg7Qj9idixkMQjoljgDmOQhDhNg6hYQlBnpB2o8QBTmVEMkWQnViSkXmnQlBnpB2o8QB2o8HolAQEXi3FJgoQE+glExBoQgjgrgagoQjPk7BLlxQBNlwE7jQQE7jPFxBLQFwBNDQE7QBmCdAgCxQBzihClhqQFyjzGyBZQCFAbByA2QgggrgXgzQhPixBFi1QBFi1CxhPQBlgtBuAFQBqAEBeAzQgJgQgGgPQgzhyAsh1QAsh0BzgzQBxgzB1AsQB1AtAzByQAZA5ABA8QAugvA8gaQCGg8CJA0QCJA1A8CGQAdBCACBIQAAA/gVA8IAPAPQAoAKAjAUQCflSE/jLQFYjaGYATQGmASE6D6QAeiDBshYQCChpCnARQBTAJBGAnQgXhVAKhXQAVjECYh8QCah9DEAVQBdAJBSAsQAGgkAIgjQBZlvFCjEQCrhoDHgWQDAgWC5A6Qg/lXBzlEQhNAwhiAKQinAOiBhrQhAg2glhHQgcBTg4BCQh/CXjEASQjFASiXh/QhKg+gshWQgrhTgHheQhgAbhggUQhigUhPhCQiBhsgPimQgPioBsiAQA5hFBRgmQBNgkBXgCQhWiaAPixQAPi0B1iMQCZi3DugWQCQgNB8A0QAChpAahsQBZluFBjEQCshpDHgWQDAgWC5A7QhImGCfltQCjl1FdjVQHKkXIJB9QFvBZD3D+QApgfAtgbQCshpDHgWQC+gWC5A7QhImGCfltQCjl1FdjVQHKkXIJB9QIJB/EYHLQBkCjAvC6QAuCygFC5QCfjKDZiDQHTkdIPBlIARgpQCkl1FdjVQHJkXIKB9QIIB/EYHLQBlCjAvC6QAUBMAKBNQDmh2Dwg1QHOj2IKB+QI4CLEwHyQApBDAhBFQDMDiCfEqQCsE/BQFqQBPFbgJFqQEPmLFyj/QNSpTPKEMQPIEOIIPNQIGPPjqRTQjsRWtSJRQnmFTozA3QogAzoDjeQA5BVArBQQFOJ0iWLLQgTBbgaBWQJGQjkMSvQkSTDvbKLQo1F1qNA8Qp5A5pWj1QBDBeAxBYQGEKxiuMSQhQFjiuEZQCPEugQFnQgcJImuGLQmxGKpHgbQlOgPkhihQkEiSi0jvIgYACQABAigCAgQgRF4kWD/QkWD+l4gRIgzgDIgBAZQgcJImuGKQmxGKpHgaQlOgPkhihQkXidi7kHQADA3gCAwQgQFhj2D2QhzEBjgDOQmxGKpHgaQlMgPkhihQkXidi7kHQADA3gCAwQgRF4kWD/QkWD9l4gQQl5gRj/kWQhZhjg4hvQkwCSlrgQQiAgGh6gcQjLDqkKC2QpfGeqsAAQj8AAkGg4gEi12AUBIgRgWIgLAMIAcAKIAAAAgEA2shxPIANgZIgrgQIAeApg");
	this.shape.setTransform(1410.8,1081.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,2821.7,2163.3);


(lib.Símbolo3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00B5D1").s().p("EgdOCoZQoJh/kYnLQhkijgvi6QguiyAFi5QifDKjZCDQnTEdoPhlIgRApQikF1ldDVQnJEXoKh9QoIh/kYnLQhlijgvi6QgUhMgKhNQjmB2jwA1QnOD2oKh+Qo4iLkwnyQgphDghhFQjMjiifkqQisk/hQlqQhPlbAJlqQkPGLlyD/QtSJTvKkMQvIkOoIvNQoGvPDqxTQDsxWNSpRQHmlTIzg3QIggzIDDeQg5hVgrhQQlOp0CWrLQAThbAahWQpGwjEMyvQESzDPbqLQI1l1KNg8QJ5g5JWD1QhDhegxhYQmEqxCusSQBQljCukZQiPkuAQlnQAcpIGumLQGxmKJHAbQFOAPEhChQEECSC0DvIAYgCQgBgiACggQARl4EWj/QEWj+F4ARIAzADIABgZQAcpIGumKQGxmKJHAaQFOAPEhChQEXCdC7EHQgDg3ACgwQAQlhD2j2QBzkBDgjOQGxmKJHAaQFMAPEhChQEXCdC7EHQgDg3ACgwQARl4EWj/QEWj9F4AQQF5ARD/EWQBZBjA4BvQEwiSFrAQQCAAGB6AcQDLjqEKi2QM/o3PODRQPNDTIlNhQDFE0BjFiQBiFTACFlQEZmPGKkJQOIpqQmDkQQlDmJWOrQDkFoBtF/QIjB/E4HYQFBHph2I8Qh2I+noFAQi3B4jMA7QD9CdCxEMQDoFjADGOQBDBNA6BYQFBHph2I8QhTGVkMEWQHVCSEXGnQFBHph2I8Qh2I8noFAQkXC3lJAoQk+AlkxhoQAjArAaAoQDPE7hLFxQhNFwk7DQQk7DPlxhLQlwhNjQk7QhmidggixQhzChilBqQlyDzmyhZQj6g0i7iRQgSF5kVD9QkXD+l4gRQjJgJixhcQishah4iYQifFslQDWQkEClkpAdIAHAJQBpCCgRCnQgRCniCBqQiCBpingRQhTgJhGgnQAXBVgKBXQgVDEiYB8QiaB9jEgVQhggKhVguQgxgbgpgmQAMAYAKAZQA5CehGCYQgmBRhEA5QhCA4hTAYQB7B+AgCvQAfCyhNClQhjDZjgBTQjhBRjZhlQhNgjg/g5Qg9g3gshGQgJBzgwBmQhuDsj0BaQifA6ibgaQBXAdBSAwQDEB0B4DDQDEFDhZFuQhZFulBDEQisBpjHAWQjAAWi5g7QBIGGifFtQijF1ldDVQnKEXoJh9QlvhZj3j+QgpAfgtAbQisBpjHAWQi+AWi5g7QBIGGifFtQijF1ldDVQk8DBlaAAQicAAihgngEg2NBx5IgegpIgNAZIArAQIAAAAgEAxyBhPQgbgKgbgNQgjgQgggTIgJAqQBCADBAANIAAAAgEAv4BPpQBYg2BngYIgqgRQhGgggxgyQgJBZgVBYgEA7JAtQIAbAPQDEBzB3DEQDFFDhZFtIgEAOQBAALA/AdQAeAOAbARQAOhCAjg7QAshJBGgyQidhQhXiaQhXifATi1QATi8B4iGQj0hIimi8QhUCqh+CHgEBRRArhIgIgiIgVAMIAdAWIAAAAgEC2IgTqIALgMIgcgKIARAWg");
	this.shape.setTransform(1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,2821.7,2163.3);


(lib.Símbolo1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAACfQgdAAgbgKQAAAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAABQABAAAAAAQAZAJAbAAIABAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgBAAgAA6CTQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQAagLAVgVQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQgWAXgcALIgCABIgCAAgAhqB1IgFgFQgWgVgMgaQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAQAAABAAAAQALAYAVAUIAEAEQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIgBAAIgDgBgACNA/QAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBABAAQAKgaAAgeIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABgBAAABQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABABAAQAAABAAAAIAAAKQAAAggLAcQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABIgCAAIgCAAgAidAHQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgDQAAgbAJgaQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQgJAXAAAaIAAADQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAABQgBgBAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAgACJg+QAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQgKgWgTgSIgIgHQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABAAQAAgBAAAAQABAAABAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIAIAIQAUAUALAWQAAABABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQgBABAAAAIgCABIgCgBgAh2hhQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBIAHgHQAUgVAZgLQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgXALgTATIgHAHQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBABIAAAAIgEgCgAAwiMQgXgIgZAAIgFAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAFAAQAbAAAYAIQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQgBAAAAABIgCAAIgCAAg");
	this.shape.setTransform(15.5,15.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F1C464").s().p("AhEBFQgdgcAAgpQAAgnAdgdQAdgdAnAAQAoAAAdAdQAdAdAAAnQAAApgdAcQgdAdgoAAQgnAAgdgdg");
	this.shape_1.setTransform(15.5,15.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,33,32.9);


(lib.linea_textos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EB7SAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEB5aAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEB3hAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEB1qAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBzyAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBx5AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEBwCAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBuKAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBsRAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEBqaAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBoiAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBmpAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEBkyAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBi6AAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBhBAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBfJAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBdSAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEBbZAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBZhAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBXqAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEBVxAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBT5AAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBSCAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEBQJAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBORAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBMaAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEBKhAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBIpAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBGyAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEBE5AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEBDBAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEBBKAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEA/RAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEA9ZAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEA7iAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEA5pAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEA3xAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEA16AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEA0BAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEAyJAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEAwSAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEAuZAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEAshAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEAqqAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEAoxAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEAm5AAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEAlCAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEAjJAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEAhRAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAfaAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAdhAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAbpAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAZyAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAX5APQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAWBAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAUKAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgASRAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAQZAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAOiAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAMpAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAKxAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAI6APQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAHBAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAFJAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgADSAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgABZAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAgdAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA7AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAiUAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAkNAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAmFAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAn8APQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAp1APQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgArtAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAtkAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgAvdAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgAxVAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgAzMAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgA1FAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgA29APQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgA40APQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgA6tAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgA8lAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgA+cAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEggVAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEgiNAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEgkEAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEgl9AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEgn0AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEgpsAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEgrlAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEgtcAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA8AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEgvUAAPQgHgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEgxNAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEABAFQgBAGgEAEQgEAEgGABgEgzFAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEg08AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEg21AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEg4tAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEg6kAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEg8dAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEg+VAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhAMAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhCFAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhD9AAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhF0AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhHtAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhJlAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhLcAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhNVAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhPNAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhREAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhS9AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhU1AAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhWsAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhYlAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhadAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhcUAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEheNAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhgFAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhh8AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhj1AAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhltAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhnkAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhpdAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhrVAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhtMAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEhvFAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEhw9AAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEhy0AAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEh0tAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEh2lAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABgEh4cAAPQgHgBgEgEQgEgEgBgGQABgFAEgEQAEgEAHgBIA7AAQAHABAEAEQAEAEAAAFQAAAGgEAEQgEAEgHABgEh6VAAPQgGgBgEgEQgEgEAAgGQAAgFAEgEQAEgEAGgBIA8AAQAHABAEAEQAEAEABAFQgBAGgEAEQgEAEgHABgEh8NAAPQgGgBgEgEQgEgEgBgGQABgFAEgEQAEgEAGgBIA9AAQAGABAEAEQAEAEAAAFQAAAGgEAEQgEAEgGABg");
	this.shape.setTransform(372.9,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-423.6,-1.5,1593,3);


(lib.Interpolación10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FBB735").p("AFOAAQAACKhiBiQhiBiiKAAQiJAAhihiQhihiAAiKQAAiJBihiQBihiCJAAQCKAABiBiQBiBiAACJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.4,-34.4,68.8,68.8);


(lib.Interpolación9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FBB735").p("AFOAAQAACKhiBiQhiBiiKAAQiJAAhihiQhihiAAiKQAAiJBihiQBihiCJAAQCKAABiBiQBiBiAACJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.4,-34.4,68.8,68.8);


(lib.Interpolación6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#091832").s().p("AJ5DVQgbgbAAgoQAAgwAqggQAqgiBAAAQASAAAWAIQAAhKhEgBQg0ABgcAcIgXgvQAPgMAdgKQAbgJAaAAQBEAAAfAfQAfAfAABBIAABxQAAApAZAOIAAAcQgiAAgRgJQgRgKgHgXQgiAqhFABQglAAgbgbgAKxBfQgbAWAAAeQAAAwA6AAQAqABAggoIAAhNQgagFgLgBQgqABgaAVgAFbDEQgqgrAAhKQAAhKArgrQAsguBLAAQAZAAAcAKQAdAKANALIgcAoQgIgJgVgHQgWgJgVABQgtAAgbAfQgbAfAAA2QAAA4AcAdQAbAdAwAAQAmAAAmgeIAWAwQgtAdhCAAQhAgBgqgrgAhrDXIATg1QAvAfAcAAQAyAAAAgsQAAgfgwgWQgmgSgNgJQgOgJgKgLQgJgMgFgNQgFgNAAgNQAAgnAcgWQAcgVAuAAQAgAAA0AVIgQA0QghgbggABQgTAAgOAJQgOAJAAAPQAAAcAjAQIAmASQAkARARAVQARAVAAAhQAAApgeAYQgeAZgyAAQgygBgrgYgAmGDSQgcgeAAg3IAAjMIA4AAIAADHQAABIA/ABQAcAAAWgQQAXgQAIgVIAAjbIA3AAIAAE4Ig3AAIAAgrQgKATgcAPQgcAQgbAAQg0gBgbgdgAqgDwIhgkYIgyERIg4AAIBQmqIAbAAIBmE2IBfk2IAaAAIBXGqIg4AAIgzkRIhdEYgAC1DpIAAkIIgrAAIAAgwIBjAAIAAE4gAC8iKQgLgLAAgOQAAgOAKgKQAKgKAPAAQAOAAAKAKQAKALAAANQAAAOgKALQgKAKgOAAQgOAAgKgKgAlZiNIAyhhIA6AAIhDBhg");
	this.shape.setTransform(-74.8,89.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcDFQgbgbAAgoQAAgwAqggQAogiBAAAQASAAAWAIQAAhKhEAAQg0AAgaAcIgXgvQAPgMAbgKQAbgJAaAAQBEAAAfAfQAfAfAABCIAABwQAAAqAZANIAAAcQgiAAgRgJQgRgKgHgWQgiAqhFAAQgjAAgbgbgAAaBPQgaAWAAAeQAAAxA5AAQAqAAAggoIAAhMQgagGgLAAQgqAAgaAVgAjTCBIAAlgIA4AAIAAFXQAAAZAPAOQAOAPAXAAIAAAyQhsAAAAhfg");
	this.shape_1.setTransform(-204.5,91.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-225.7,65.8,238.5,48);


(lib.Interpolación4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#091832").s().p("ACLEKQgigKgVgQIAfgsQAwAgApAAQAmAAAWgNQAWgNAAgTQAAgmg3AAQgKAAgYAEQgZAFgOAAQhDAAAAgyQAAgQAQgNQAQgMAXgGQhCgfAAhLQAAgxAighQAiggAzAAQAuAAAaATIAcgiIAkAjIghAZQAVAcAAAsQAAAugdAgQgeAggwAFIguAFQgIABgOAFQgOAFAAAJQAAAMAdAAQAMAAAbgEQAbgFANAAQAuAAAaAWQAaAWAAAoQAAArgnAbQgnAag7AAQgfAAghgLgACbhiQgSAUAAAeQAAAhASATQARAWAeAAQAeAAARgVQAQgTAAgiQAAgegRgUQgTgVgbAAQgdAAgSAVgAK6CIIAUg1QAvAeAcAAQAzAAAAgrQAAgfgxgWQgngRgNgIQgNgJgKgMQgKgLgFgNQgFgNAAgPQAAgnAcgWQAdgVAtAAQAiAAA0AVIgPA0QghgbgiAAQgUAAgNAKQgOAJAAAPQAAAeAiAPIAoASQAlARAQAUQARAVAAAgQAAAqgeAYQgdAYg1AAQgxAAgsgYgAGeB0QgmgsAAhJQAAhJAogtQAngsA/AAQBEAAAlArQAlAqAABNQAABKgmArQgmAshCAAQhDAAglgsgAHKhXQgXAfAAA3QAAB0BTAAQAnAAAXggQAWggAAg0QAAh1hUAAQgmAAgWAfgAtrCFQgbgbAAgnQAAgwAqgfQApghBBAAQASAAAWAIQAAhNhEAAQg0AAgcAdIgYgvQAQgNAcgJQAcgJAZAAQBFAAAfAfQAeAfAABDIAABvQAAApAZAOIAAAcQgiAAgRgKQgRgKgHgWQghAqhFAAQglAAgbgbgAs0AQQgbAWAAAdQAAAxA6AAQAqAAAhgoIAAhMQgbgEgKAAQgqAAgbAUgAguCaIAAkJIgrAAIAAgvIBgAAIAAE4gAjQCaIAAjEQAAhLhAAAQgUAAgSANQgRAMgHAQIAADmIg4AAIAAjdQAAgXgRgNQgRgOgdAAQgRAAgTANQgTANgIAQIAADlIg3AAIAAk4IAkAAIATAlQAggqAwAAQBEAAAaAqQAKgSAZgMQAagMAbAAQAwAAAbAdQAbAcAAA0IAADQgAgojZQgKgLAAgOQAAgOAKgKQAKgKAOAAQAPAAAIAKQAKAKAAAOQAAAOgKALQgIAKgPAAQgOAAgKgKg");
	this.shape.setTransform(412.3,105.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ADKDCIATg1QAvAfAcAAQA0AAAAgsQAAgfgygWQgmgSgNgJQgOgJgKgLQgJgMgFgNQgFgLAAgPQAAgnAcgVQAcgWAuAAQAiAAA0AWIgQAzQghgaghAAQgUAAgOAJQgOAKAAAOQAAAcAjAQIAoASQAkARARAVQARAVAAAhQAAAqgeAYQgeAYg0AAQgyAAgrgZgAjMDbIhgkYIgyESIg4AAIBQmrIAbAAIBmE3IBfk3IAaAAIBVGrIg2AAIgzkSIhdEYgABODVIAAkJIgrAAIAAgvIBjAAIAAE4gABVifQgLgKAAgOQAAgPAKgKQAKgKAPAAQAOAAAKALQAKAKAAAOQAAAOgKAKQgKAKgOAAQgOAAgKgKg");
	this.shape_1.setTransform(258.8,99.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(218.1,78,284.5,55.6);


(lib.Interpolación2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EAh6ACzQgmgsAAhLQAAhHAngsQAngtBAAAQBDAAAmArQAlArAABKQAABMgmAsQgmAshCAAQhDAAglgtgEAimgAXQgYAdAAA2QABB2BTAAQAnAAAWgfQAXggAAg3QAAhyhUAAQgmAAgWAfgASiDFQgbgbAAgoQAAgwAqggQAqgiBAAAQASAAAWAIQAAhKhEAAQg0AAgcAcIgYgvQAQgMAcgKQAcgJAZAAQBFAAAfAfQAfAfAABCIAABwQgBAqAZANIAAAcQghAAgRgJQgSgKgHgWQghAqhFAAQglAAgbgbgATaBPQgbAWAAAeQAAAxA5AAQAqAAAhgoIAAhMQgagGgLAAQgqAAgaAVgAOEC1QgqgsgBhJQAAhJAsgtQAsguBLAAQAYAAAdAKQAdALANAKIgcAoQgJgJgVgHQgVgIgVAAQgtAAgbAgQgbAeAAA3QAAA3AcAdQAbAdAwAAQAmAAAlgdIAXAvQguAdhCAAQg/AAgqgrgAI/DCQgcgeAAg2IAAjMIA4AAIAADGQAABJA/AAQAbAAAXgQQAXgQAIgVIAAjaIA3AAIAAE4Ig3AAIAAgsQgKATgcAPQgdAQgbAAQgzAAgbgegAhUC3QgugsAAhKQAAhMAvgvQArgqA3AAQBDAAAmAmQAlAkAAA6QAAATgEAPIjgAAQAAA3AeAeQAaAaApAAQAvAAAggcIAYAoQgOANgaAJQghANgqAAQg4AAgqgpgAgqgdQgZAXgDAgICsAAQAAgggVgWQgYgZgnAAQgkAAgYAYgApQC3QgugsAAhKQAAhMAvgvQAqgqA6AAQBDAAAnAmQAkAkAAA6QAAATgEAPIjjAAQABA3AeAeQAbAaApAAQAwAAAggcIAYAoQgNANgbAJQgiANgoAAQg7AAgqgpgAongdQgXAXgEAgICuAAQAAgggWgWQgWgZgoAAQgmAAgZAYgAspDEQgagcAAgqIAAiwIglAAIAAgsIAlAAIAAhCIA3gVIAABXIBWAAIAAAsIhWAAIAACaQAAAnANARQAOARAdAAQAWAAAWgLIAJAxQgiAJgqAAQgmAAgYgcgA1uC3QgugsAAhKQAAhMAvgvQArgqA5AAQBDAAAmAmQAlAkAAA6QAAATgEAPIjjAAQAAA3AfAeQAaAaAqAAQAwAAAggcIAYAoQgNANgbAJQghANgqAAQg6AAgqgpgA1EgdQgZAXgDAgICuAAQAAgggVgWQgYgZgnAAQglAAgZAYgA72DgIiGk/IA8AAIBUDaIBUjaIA6AAIiKE/gActC1QgkgqAAhGQgBhFAqgyQArgyA6AAQAxAAAZAXIAAiSIA3AAIAAG4Ig3AAIAAgXQgdAdg4AAQg6AAglgqgAdfgUQgcAgAAAzQAAByBnAAQANAAATgIQASgJAFgJIAAisQgVggglAAQgsAAgcAhgADrC1QglgqAAhGQAAhFAqgyQAqgyA7AAQAwAAAaAXIAAiSIA3AAIAAG4Ig3AAIAAgXQgdAdg4AAQg7AAgkgqgAEcgUQgcAgAAAzQAAByBoAAQANAAASgIQATgJAFgJIAAisQgVggglAAQgtAAgcAhgAaTDaIAAi3QAAgwgPgUQgPgUgkAAQgSAAgWALQgUAMgMARIAADnIg3AAIAAk4IAmAAIARAoQAdguA9AAQBoAAAAB8IAADCgAw8DaIAAk4IA3AAIAAAyQAfg4A8AAQAPAAAcAFIgXA3QgSgNgTAAQgdAAgWAbQgWAagBAmIAAC0gA4YDaIAAkJIgrAAIAAgvIBjAAIAAE4gA/oDaIAAkJIgrAAIAAgvIBiAAIAAE4gEglvADaIAAmrIBqgDQBaAAA0A2QA1A3AABbQAADmjWAAgEgk0gCdIAAE/QATADAdAAQA+AAAjguQAjguAAhQQAAiZiJAAIgrADgA4RiaQgKgKAAgOQgBgPALgKQAKgKAOAAQAPAAAJALQAKAKAAAOQAAAOgKAKQgJAKgPAAQgOAAgKgKgA/iiaQgLgKAAgOQAAgPAKgKQAKgKAPAAQAPAAAKALQAJAKABAOQgBAOgJAKQgKAKgPAAQgOAAgKgKg");
	this.shape.setTransform(68.1,-100.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-173.5,-122.9,483.3,44.9);


(lib.CopiadeInterpolación6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#091832").s().p("AAvCeQgtg/gBhhQABhdAug/QAvg/BPAAQBZAAAxA6QAvA6AABnQAABogwA8QgvA8haAAQhRAAguhAgABbh7QgcAsAABNQAABIAdAxQAeAyA0AAQA9AAAfguQAfgtAAhQQABimh8AAQg2AAgdAtgAjcDWIAAjAIiKjrIA8AAIBrC8IBri8IA8AAIiJDrIAADAg");
	this.shape.setTransform(21.2,67.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhuCoQAiAAAagQQAZgRAAgWQgBgagIgaIgYg9IhVjZIA5AAIBaDxIBTjxIA5AAIiFFuQgLAdggAUQgkAUgqAAg");
	this.shape_1.setTransform(-48.1,79.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.5,45.7,119.7,56);


(lib.transicion_nubes_on = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_191 = function() {
		this.parent.gotoAndStop("inicio");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(191).call(this.frame_191).wait(1));

	// texto1
	this.instance = new lib.Interpolación2("synched",0);
	this.instance.setTransform(754.1,421.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({_off:false},0).to({alpha:1},15).wait(143).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// texto2
	this.instance_1 = new lib.Interpolación4("synched",0);
	this.instance_1.setTransform(669.2,421.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(57).to({_off:false},0).to({alpha:1},13).wait(102).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// texto3
	this.instance_2 = new lib.Interpolación6("synched",0);
	this.instance_2.setTransform(959.2,529.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(88).to({_off:false},0).to({alpha:1},13).wait(71).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// texto4
	this.instance_3 = new lib.CopiadeInterpolación6("synched",0);
	this.instance_3.setTransform(956.1,661.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(114).to({_off:false},0).to({alpha:1},13).wait(45).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(4));

	// linea1
	this.instance_4 = new lib.linea_textos();
	this.instance_4.setTransform(-1088.8,349.1,1,1,0,0,0,584.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({regX:372.9,x:-1225.9},0).wait(1).to({x:-1151.3},0).wait(1).to({x:-1076.7},0).wait(1).to({x:-1002.1},0).wait(1).to({x:-927.5},0).wait(1).to({x:-853},0).wait(1).to({x:-778.4},0).wait(1).to({x:-703.8},0).wait(1).to({x:-629.2},0).wait(1).to({x:-554.6},0).wait(1).to({x:-480},0).wait(1).to({x:-405.5},0).wait(1).to({x:-330.9},0).wait(1).to({x:-256.4},0).wait(1).to({x:-181.7},0).wait(1).to({x:-107.1},0).wait(1).to({x:-32.5},0).wait(1).to({x:42},0).wait(1).to({x:116.6},0).wait(1).to({x:191.2},0).wait(1).to({x:265.8},0).wait(141).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// linea2
	this.instance_5 = new lib.linea_textos();
	this.instance_5.setTransform(2635.2,547.1,1,1,0,0,0,584.6,0);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(44).to({_off:false},0).wait(1).to({regX:372.9,x:2388.3},0).wait(1).to({x:2353},0).wait(1).to({x:2317.8},0).wait(1).to({x:2282.5},0).wait(1).to({x:2247.3},0).wait(1).to({x:2212},0).wait(1).to({x:2176.8},0).wait(1).to({x:2141.5},0).wait(1).to({x:2106.3},0).wait(1).to({x:2071},0).wait(1).to({x:2035.8},0).wait(1).to({x:2000.5},0).wait(1).to({x:1965.3},0).wait(1).to({x:1930},0).wait(1).to({x:1894.8},0).wait(1).to({x:1859.5},0).wait(1).to({x:1824.3},0).wait(1).to({x:1789},0).wait(1).to({x:1753.8},0).wait(1).to({x:1718.5},0).wait(1).to({x:1683.3},0).wait(97).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// linea3
	this.instance_6 = new lib.linea_textos();
	this.instance_6.setTransform(-904.8,647.2,1,1,0,0,0,584.6,0);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(75).to({_off:false},0).wait(1).to({regX:372.9,x:-1040.4},0).wait(1).to({x:-964.3},0).wait(1).to({x:-888.2},0).wait(1).to({x:-812.1},0).wait(1).to({x:-736.1},0).wait(1).to({x:-660},0).wait(1).to({x:-583.9},0).wait(1).to({x:-507.8},0).wait(1).to({x:-431.8},0).wait(1).to({x:-355.7},0).wait(1).to({x:-279.6},0).wait(1).to({x:-203.5},0).wait(1).to({x:-127.5},0).wait(1).to({x:-51.4},0).wait(1).to({x:24.7},0).wait(1).to({x:100.8},0).wait(1).to({x:176.8},0).wait(70).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// linea4
	this.instance_7 = new lib.linea_textos();
	this.instance_7.setTransform(2945.7,755.3,1,1,0,0,0,584.6,0);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(106).to({_off:false},0).wait(1).to({regX:372.9,x:2640.2},0).wait(1).to({x:2546.5},0).wait(1).to({x:2452.8},0).wait(1).to({x:2359},0).wait(1).to({x:2265.3},0).wait(1).to({x:2171.6},0).wait(1).to({x:2077.9},0).wait(1).to({x:1984.1},0).wait(1).to({x:1890.3},0).wait(1).to({x:1796.6},0).wait(1).to({x:1702.9},0).wait(45).to({alpha:0.909},0).wait(1).to({alpha:0.818},0).wait(1).to({alpha:0.727},0).wait(1).to({alpha:0.636},0).wait(1).to({alpha:0.545},0).wait(1).to({alpha:0.455},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.273},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.091},0).wait(1).to({alpha:0},0).wait(12).to({_off:true},1).wait(7));

	// Capa 9
	this.instance_8 = new lib.Símbolo6();
	this.instance_8.setTransform(718.1,427.5,1,1,0,0,0,473.4,271.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(155).to({regX:414.2,regY:259.7,x:688.9,y:438.1},0).wait(1).to({x:718.9,y:460.7},0).wait(1).to({x:749,y:483.3},0).wait(1).to({x:779,y:505.9},0).wait(1).to({x:809.1,y:528.5},0).wait(1).to({x:839.1,y:551.1},0).wait(1).to({x:869.1,y:573.7},0).wait(1).to({x:899.2,y:596.3},0).wait(1).to({x:929.2,y:618.9},0).wait(1).to({x:959.3,y:641.5},0).wait(1).to({x:989.3,y:664.1},0).wait(1).to({x:1019.3,y:686.7},0).wait(1).to({x:1049.4,y:709.3},0).wait(1).to({x:1079.4,y:731.9},0).wait(1).to({x:1109.5,y:754.5},0).wait(1).to({x:1139.5,y:777.1},0).wait(1).to({x:1169.5,y:799.7},0).wait(1).to({x:1199.6,y:822.3},0).wait(1).to({x:1229.6,y:844.9},0).wait(1).to({x:1259.7,y:867.5},0).wait(1).to({x:1289.7,y:890.1},0).wait(1).to({x:1319.7,y:912.7},0).wait(1).to({x:1349.8,y:935.3},0).wait(1).to({x:1379.8,y:957.9},0).wait(1).to({x:1409.8,y:980.5},0).wait(1).to({x:1439.9,y:1003.1},0).wait(1).to({x:1469.9,y:1025.7},0).wait(1).to({x:1500,y:1048.3},0).wait(1).to({x:1530,y:1070.9},0).wait(1).to({x:1560.1,y:1093.5},0).wait(1).to({x:1590.1,y:1116.1},0).wait(1).to({x:1620.1,y:1138.7},0).wait(1).to({x:1650.2,y:1161.3},0).wait(1).to({x:1680.2,y:1183.9},0).wait(1).to({x:1710.3,y:1206.5},0).wait(1).to({x:1740.3,y:1229.2},0).to({_off:true},1).wait(1));

	// Capa 8
	this.instance_9 = new lib.Símbolo5();
	this.instance_9.setTransform(1070.3,714.7,1,1,0,0,0,281.4,178.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(155).to({regX:281.5,x:1041.5,y:693.8},0).wait(1).to({x:1012.7,y:672.9},0).wait(1).to({x:983.9,y:652.1},0).wait(1).to({x:955.1,y:631.2},0).wait(1).to({x:926.3,y:610.3},0).wait(1).to({x:897.4,y:589.5},0).wait(1).to({x:868.6,y:568.6},0).wait(1).to({x:839.8,y:547.7},0).wait(1).to({x:811,y:526.9},0).wait(1).to({x:782.2,y:506},0).wait(1).to({x:753.4,y:485.1},0).wait(1).to({x:724.5,y:464.3},0).wait(1).to({x:695.7,y:443.4},0).wait(1).to({x:666.9,y:422.6},0).wait(1).to({x:638.1,y:401.7},0).wait(1).to({x:609.3,y:380.8},0).wait(1).to({x:580.4,y:360},0).wait(1).to({x:551.6,y:339.1},0).wait(1).to({x:522.8,y:318.2},0).wait(1).to({x:494,y:297.4},0).wait(1).to({x:465.2,y:276.5},0).wait(1).to({x:436.4,y:255.6},0).wait(1).to({x:407.5,y:234.8},0).wait(1).to({x:378.7,y:213.9},0).wait(1).to({x:349.9,y:193.1},0).wait(1).to({x:321.1,y:172.2},0).wait(1).to({x:292.3,y:151.4},0).wait(1).to({x:263.5,y:130.5},0).wait(1).to({x:234.7,y:109.6},0).wait(1).to({x:205.9,y:88.8},0).wait(1).to({x:177,y:67.9},0).wait(1).to({x:148.2,y:47.1},0).wait(1).to({x:119.4,y:26.2},0).wait(1).to({x:90.6,y:5.3},0).wait(1).to({x:61.8,y:-15.5},0).wait(1).to({x:32.9,y:-36.4},0).to({_off:true},1).wait(1));

	// Capa 7
	this.instance_10 = new lib.Símbolo3();
	this.instance_10.setTransform(678.7,534.2,1,1,0,0,0,1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(155).to({x:630.1,y:499.5},0).wait(1).to({x:581.5,y:464.9},0).wait(1).to({x:533,y:430.2},0).wait(1).to({x:484.4,y:395.5},0).wait(1).to({x:435.8,y:360.9},0).wait(1).to({x:387.2,y:326.2},0).wait(1).to({x:338.7,y:291.6},0).wait(1).to({x:290.1,y:256.9},0).wait(1).to({x:241.5,y:222.2},0).wait(1).to({x:192.9,y:187.6},0).wait(1).to({x:144.3,y:152.9},0).wait(1).to({x:95.8,y:118.2},0).wait(1).to({x:47.2,y:83.6},0).wait(1).to({x:-1.3,y:49},0).wait(1).to({x:-50,y:14.3},0).wait(1).to({x:-98.5,y:-20.4},0).wait(1).to({x:-147.1,y:-55.1},0).wait(1).to({x:-195.7,y:-89.7},0).wait(1).to({x:-244.3,y:-124.4},0).wait(1).to({x:-292.9,y:-159.1},0).wait(1).to({x:-341.4,y:-193.7},0).wait(1).to({x:-390,y:-228.4},0).wait(1).to({x:-438.6,y:-263},0).wait(1).to({x:-487.2,y:-297.7},0).wait(1).to({x:-535.7,y:-332.4},0).wait(1).to({x:-584.3,y:-367},0).wait(1).to({x:-632.9,y:-401.7},0).to({_off:true},1).wait(10));

	// Capa 1
	this.instance_11 = new lib.Símbolo4();
	this.instance_11.setTransform(1286.2,816.3,1,1,0,0,0,1410.8,1081.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(155).to({regY:1081.6,x:1328.7,y:843.4},0).wait(1).to({x:1371.1,y:870.5},0).wait(1).to({x:1413.5,y:897.7},0).wait(1).to({x:1455.9,y:924.8},0).wait(1).to({x:1498.4,y:952},0).wait(1).to({x:1540.8,y:979.1},0).wait(1).to({x:1583.2,y:1006.2},0).wait(1).to({x:1625.7,y:1033.4},0).wait(1).to({x:1668.1,y:1060.6},0).wait(1).to({x:1710.5,y:1087.7},0).wait(1).to({x:1752.9,y:1114.8},0).wait(1).to({x:1795.4,y:1142},0).wait(1).to({x:1837.8,y:1169.1},0).wait(1).to({x:1880.2,y:1196.2},0).wait(1).to({x:1922.7,y:1223.4},0).wait(1).to({x:1965.1,y:1250.6},0).wait(1).to({x:2007.5,y:1277.7},0).wait(1).to({x:2050,y:1304.9},0).wait(1).to({x:2092.4,y:1332},0).wait(1).to({x:2134.8,y:1359.2},0).wait(1).to({x:2177.3,y:1386.3},0).wait(1).to({x:2219.7,y:1413.5},0).wait(1).to({x:2262.1,y:1440.6},0).wait(1).to({x:2304.6,y:1467.8},0).wait(1).to({x:2347,y:1494.9},0).wait(1).to({x:2389.4,y:1522.1},0).wait(1).to({x:2431.9,y:1549.3},0).to({_off:true},1).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2097,-547.5,4794.1,2445.4);


(lib.transicion_nubes_off = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{play:0});

	// timeline functions:
	this.frame_36 = function() {
		/* Detener en este fotograma
		La línea de tiempo se detendrá/pausará en el fotograma en el que se inserte este código.
		También se puede utilizar para detener/pausar la línea de tiempo de clips de película.
		*/
		
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(36).call(this.frame_36).wait(1));

	// Capa 9
	this.instance = new lib.Símbolo6();
	this.instance.setTransform(1799.5,1241.2,1,1,0,0,0,473.4,271.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:414.2,regY:259.7,x:1710.3,y:1206.5},0).wait(1).to({x:1680.2,y:1183.9},0).wait(1).to({x:1650.2,y:1161.3},0).wait(1).to({x:1620.1,y:1138.7},0).wait(1).to({x:1590.1,y:1116.1},0).wait(1).to({x:1560.1,y:1093.5},0).wait(1).to({x:1530,y:1070.9},0).wait(1).to({x:1500,y:1048.3},0).wait(1).to({x:1469.9,y:1025.7},0).wait(1).to({x:1439.9,y:1003.1},0).wait(1).to({x:1409.9,y:980.5},0).wait(1).to({x:1379.8,y:957.9},0).wait(1).to({x:1349.8,y:935.3},0).wait(1).to({x:1319.7,y:912.7},0).wait(1).to({x:1289.7,y:890.1},0).wait(1).to({x:1259.7,y:867.5},0).wait(1).to({x:1229.6,y:844.9},0).wait(1).to({x:1199.6,y:822.3},0).wait(1).to({x:1169.5,y:799.7},0).wait(1).to({x:1139.5,y:777.1},0).wait(1).to({x:1109.5,y:754.5},0).wait(1).to({x:1079.4,y:731.9},0).wait(1).to({x:1049.4,y:709.3},0).wait(1).to({x:1019.3,y:686.7},0).wait(1).to({x:989.3,y:664.1},0).wait(1).to({x:959.3,y:641.5},0).wait(1).to({x:929.2,y:618.9},0).wait(1).to({x:899.2,y:596.3},0).wait(1).to({x:869.1,y:573.7},0).wait(1).to({x:839.1,y:551.1},0).wait(1).to({x:809.1,y:528.5},0).wait(1).to({x:779,y:505.9},0).wait(1).to({x:749,y:483.3},0).wait(1).to({x:718.9,y:460.7},0).wait(1).to({x:688.9,y:438.1},0).wait(1).to({x:658.9,y:415.5},0).wait(1));

	// Capa 8
	this.instance_1 = new lib.Símbolo5();
	this.instance_1.setTransform(32.8,-36.4,1,1,0,0,0,281.4,178.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:281.5,x:61.8,y:-15.5},0).wait(1).to({x:90.6,y:5.3},0).wait(1).to({x:119.4,y:26.2},0).wait(1).to({x:148.2,y:47.1},0).wait(1).to({x:177,y:67.9},0).wait(1).to({x:205.9,y:88.8},0).wait(1).to({x:234.7,y:109.6},0).wait(1).to({x:263.5,y:130.5},0).wait(1).to({x:292.3,y:151.4},0).wait(1).to({x:321.1,y:172.2},0).wait(1).to({x:349.9,y:193.1},0).wait(1).to({x:378.7,y:213.9},0).wait(1).to({x:407.5,y:234.8},0).wait(1).to({x:436.4,y:255.6},0).wait(1).to({x:465.2,y:276.5},0).wait(1).to({x:494,y:297.4},0).wait(1).to({x:522.8,y:318.2},0).wait(1).to({x:551.6,y:339.1},0).wait(1).to({x:580.4,y:360},0).wait(1).to({x:609.3,y:380.8},0).wait(1).to({x:638.1,y:401.7},0).wait(1).to({x:666.9,y:422.6},0).wait(1).to({x:695.7,y:443.4},0).wait(1).to({x:724.5,y:464.3},0).wait(1).to({x:753.3,y:485.1},0).wait(1).to({x:782.2,y:506},0).wait(1).to({x:811,y:526.9},0).wait(1).to({x:839.8,y:547.7},0).wait(1).to({x:868.6,y:568.6},0).wait(1).to({x:897.4,y:589.5},0).wait(1).to({x:926.3,y:610.3},0).wait(1).to({x:955.1,y:631.2},0).wait(1).to({x:983.9,y:652.1},0).wait(1).to({x:1012.7,y:672.9},0).wait(1).to({x:1041.5,y:693.8},0).wait(1).to({x:1070.4,y:714.7},0).wait(1));

	// Capa 7
	this.instance_2 = new lib.Símbolo3();
	this.instance_2.setTransform(-632.9,-401.7,1,1,0,0,0,1410.8,1081.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).wait(1).to({x:-584.3,y:-367},0).wait(1).to({x:-535.7,y:-332.4},0).wait(1).to({x:-487.2,y:-297.7},0).wait(1).to({x:-438.6,y:-263},0).wait(1).to({x:-390,y:-228.4},0).wait(1).to({x:-341.4,y:-193.7},0).wait(1).to({x:-292.9,y:-159.1},0).wait(1).to({x:-244.3,y:-124.4},0).wait(1).to({x:-195.7,y:-89.7},0).wait(1).to({x:-147.1,y:-55.1},0).wait(1).to({x:-98.5,y:-20.4},0).wait(1).to({x:-50,y:14.3},0).wait(1).to({x:-1.4,y:48.9},0).wait(1).to({x:47.1,y:83.5},0).wait(1).to({x:95.8,y:118.2},0).wait(1).to({x:144.3,y:152.9},0).wait(1).to({x:192.9,y:187.6},0).wait(1).to({x:241.5,y:222.2},0).wait(1).to({x:290.1,y:256.9},0).wait(1).to({x:338.7,y:291.6},0).wait(1).to({x:387.2,y:326.2},0).wait(1).to({x:435.8,y:360.9},0).wait(1).to({x:484.4,y:395.5},0).wait(1).to({x:533,y:430.2},0).wait(1).to({x:581.5,y:464.9},0).wait(1).to({x:630.1,y:499.5},0).wait(1).to({x:678.7,y:534.2},0).wait(1));

	// Capa 1
	this.instance_3 = new lib.Símbolo4();
	this.instance_3.setTransform(2431.9,1549.4,1,1,0,0,0,1410.8,1081.7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).wait(1).to({regY:1081.6,x:2389.4,y:1522.1},0).wait(1).to({x:2347,y:1494.9},0).wait(1).to({x:2304.6,y:1467.8},0).wait(1).to({x:2262.1,y:1440.6},0).wait(1).to({x:2219.7,y:1413.5},0).wait(1).to({x:2177.3,y:1386.3},0).wait(1).to({x:2134.9,y:1359.2},0).wait(1).to({x:2092.4,y:1332},0).wait(1).to({x:2050,y:1304.9},0).wait(1).to({x:2007.5,y:1277.7},0).wait(1).to({x:1965.1,y:1250.6},0).wait(1).to({x:1922.7,y:1223.4},0).wait(1).to({x:1880.2,y:1196.3},0).wait(1).to({x:1837.9,y:1169.2},0).wait(1).to({x:1795.4,y:1142},0).wait(1).to({x:1752.9,y:1114.8},0).wait(1).to({x:1710.5,y:1087.7},0).wait(1).to({x:1668.1,y:1060.6},0).wait(1).to({x:1625.7,y:1033.4},0).wait(1).to({x:1583.2,y:1006.3},0).wait(1).to({x:1540.8,y:979.1},0).wait(1).to({x:1498.4,y:952},0).wait(1).to({x:1455.9,y:924.8},0).wait(1).to({x:1413.5,y:897.7},0).wait(1).to({x:1371.1,y:870.5},0).wait(1).to({x:1328.7,y:843.4},0).wait(1).to({x:1286.2,y:816.2},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-248.6,-214.9,2403,1727.8);


(lib.scene04_boton1_anim = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 2 copia
	this.instance = new lib.Interpolación9("synched",0);
	this.instance.setTransform(33.4,33.4);
	this.instance._off = true;

	this.instance_1 = new lib.Interpolación10("synched",0);
	this.instance_1.setTransform(33.4,33.4,1.501,1.501);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},14).to({state:[{t:this.instance_1}]},29).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({_off:false},0).to({_off:true,scaleX:1.5,scaleY:1.5,alpha:0},29).wait(1));

	// Capa 2
	this.instance_2 = new lib.Interpolación9("synched",0);
	this.instance_2.setTransform(33.4,33.4);

	this.instance_3 = new lib.Interpolación10("synched",0);
	this.instance_3.setTransform(33.4,33.4,1.501,1.501);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},29).to({state:[]},1).wait(14));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true,scaleX:1.5,scaleY:1.5,alpha:0},29).wait(15));

	// Capa 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FBB735").p("AFOAAQAAAbgEAZQgCAKgCAKQgDARgFAQQgYBIg6A7QhiBiiKAAQiJAAhihiQhHhHgThdQgCgKgCgKQgEgZAAgbQAAgMABgNQADgmAKgiQADgKAEgKQAEgKAEgJQAGgOAHgNQAXgmAhgiQBihiCJAAQCKAABiBiQAhAiAXAmQAMAWAJAYQAEAKADAKQAKAiADAmQABANAAAMg");
	this.shape.setTransform(33.4,33.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(44));

	// Capa 4
	this.instance_4 = new lib.Símbolo1();
	this.instance_4.setTransform(33.5,33.5,1,1,0,0,0,15.5,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({rotation:9.4,x:33.4},0).wait(1).to({rotation:18.8,y:33.4},0).wait(1).to({rotation:28.3,y:33.5},0).wait(1).to({rotation:37.7,y:33.4},0).wait(1).to({rotation:47.1,y:33.5},0).wait(1).to({rotation:56.5},0).wait(1).to({rotation:65.9,y:33.4},0).wait(1).to({rotation:75.3,x:33.3},0).wait(1).to({rotation:84.8,y:33.5},0).wait(1).to({rotation:94.2,y:33.4},0).wait(1).to({rotation:103.6,x:33.4},0).wait(1).to({rotation:113},0).wait(1).to({rotation:122.4,x:33.3},0).wait(1).to({rotation:131.9},0).wait(1).to({rotation:141.3},0).wait(1).to({rotation:150.7},0).wait(1).to({rotation:160.1,y:33.3},0).wait(1).to({rotation:169.5},0).wait(1).to({rotation:179,y:33.4},0).wait(1).to({rotation:188.4,y:33.3},0).wait(1).to({rotation:197.8,x:33.4},0).wait(1).to({rotation:207.2},0).wait(1).to({rotation:216.6},0).wait(1).to({rotation:226},0).wait(1).to({rotation:235.5},0).wait(1).to({rotation:244.9},0).wait(1).to({rotation:254.3,y:33.4},0).wait(1).to({rotation:263.7,y:33.3},0).wait(1).to({rotation:273.1,x:33.5},0).wait(1).to({rotation:282.6},0).wait(1).to({rotation:292,x:33.4,y:33.4},0).wait(1).to({rotation:301.4,x:33.5,y:33.3},0).wait(1).to({rotation:310.8,y:33.4},0).wait(1).to({rotation:320.2,x:33.4},0).wait(1).to({rotation:329.7,x:33.5},0).wait(1).to({rotation:339.1},0).wait(1).to({rotation:348.5},0).wait(1).to({rotation:357.9,x:33.4,y:33.5},0).wait(1).to({rotation:367.3},0).wait(1).to({rotation:376.7,x:33.5},0).wait(1).to({rotation:386.2,x:33.4},0).wait(1).to({rotation:395.6,y:33.4},0).wait(1).to({rotation:405,y:33.5},0).wait(1));

	// Capa 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FBB735").p("AFOAAQAAAbgEAZQgCAKgCAKQgDARgFAQQgYBIg6A7QhiBiiKAAQiJAAhihiQhHhHgThdQgCgKgCgKQgEgZAAgbQAAgMABgNQADgmAKgiQADgKAEgKQAEgKAEgJQAGgOAHgNQAXgmAhgiQBihiCJAAQCKAABiBiQAhAiAXAmQAMAWAJAYQAEAKADAKQAKAiADAmQABANAAAMg");
	this.shape_1.setTransform(33.4,33.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C4E0DE").s().p("AjMDNQgtgugVg2QgGgQgEgRIgEgUQgFgZABgbIAAgZQAEgmAMgiIAIgUQALgYAPgWQAPgVATgUQBWhUB2AAQB4AABVBUQATAUAPAVQAPAWALAYIAIAUQAMAiADAmIABAZQAAAbgEAZIgEAUQgEARgGAQQgVA2gtAuQhVBUh4AAQh2AAhWhUg");
	this.shape_2.setTransform(33.4,33.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C4E0DE").s().p("AjMDNQhUhVAAh4QAAh2BUhWQBWhUB2AAQB4AABVBUQBUBWAAB2QAAB4hUBVQhVBUh4AAQh2AAhWhUg");
	this.shape_3.setTransform(33.4,33.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).to({state:[{t:this.shape_3}]},29).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,68.8,68.8);


(lib.scene04_boton1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Capa 1
	this.instance = new lib.scene04_boton1_anim();
	this.instance.setTransform(33.4,33.4,1,1,0,0,0,33.4,33.4);

	this.instance_1 = new lib.Símbolo1();
	this.instance_1.setTransform(33.4,33.4,0.999,0.999,-115.1,0,0,15.5,15.4);
	this.instance_1.alpha = 0.602;

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(251,183,53,0.498)").p("AFOAAQAACKhiBiQhiBiiKAAQiJAAhihiQhihiAAiKQAAiJBihiQBihiCJAAQCKAABiBiQBiBiAACJg");
	this.shape.setTransform(33.4,33.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,153,255,0.6)").s().p("AjMDNQhUhVAAh4QAAh2BUhWQBWhUB2AAQB4AABVBUQBUBWAAB2QAAB4hUBVQhVBUh4AAQh2AAhWhUg");
	this.shape_1.setTransform(33.4,33.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FBB735").s().p("AjvDwQhihkgBiMQABiLBihkQBkhiCLgBQCMABBkBiQBiBkABCLQgBCMhiBkQhkBiiMABQiLgBhkhigAjojoQhgBhABCHQgBCIBgBhQBhBgCHAAQCIAABhhgQBghhAAiIQAAiHhghhQhhhgiIABIAAAAQiHgBhhBgg");
	this.shape_2.setTransform(33.4,33.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMCdQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAQAZgDAYgLIAGgDQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAAAAAIgHADIAAAAQgZAMgbADIAAAAIgDgCgAgtCYIgIgDQgagJgTgPQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQASAOAYAJIAIADQAAAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABIgDAAIgBAAgABzBnQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAQgTAJgaIACgFQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAIgCAFQgKAcgRAUQgBABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIAAAAIgDgBgAiHBQQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgFgKQgLgWgDgYQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQAAABABAAQAAAAAAABQADAWAKAVIAFAJQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAIgDABIgBAAgACWgHQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgCgagMgZIgCgFQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABAAAAABIADAFQANAbACAcQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAIgBAAIgDgCgAiWghQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAFgOQAIgXANgSQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAABgBAAQgMARgIAVIgEAOQgBAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgCAAIgCAAgABihvQgUgRgcgLQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAdALAVATQAAAAABABQAAAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAIAAAAIgDgCgAhQh+QgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAIAPgHIABgBQAdgOAegBQABAAAAAAQABAAAAABQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgcABgcANIgBABIgOAHIgCAAIgBAAg");
	this.shape_3.setTransform(33.5,33.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C4E0DE").s().p("AjMDNQhUhVAAh4QAAh2BUhWQBWhUB2AAQB4AABVBUQBUBWAAB2QAAB4hUBVQhVBUh4AAQh2AAhWhUgABGCEIgHACQgXAMgZACQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQABABAAAAQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAagDAagMIAAAAIAGgCQABgBAAAAQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgBAAIgCABgAhfBzQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABABAAQAAABAAAAQAUAPAZAKIAJACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAIgHgDQgYgIgSgPIgDgBIgBAAgACQArQAAAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAIgCAFQgJAagQATQgBABAAAAQAAABAAAAQAAAAAAABQgBAAABABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAgBABAAQAAAAABAAQAAAAABgBQAAAAAAAAQARgVAKgbIACgFQAAgBAAAAQABgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIgBAAIgDABgAiYAPQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABQgBAAAAABQAAAAABABQADAXAKAXIAGAKQAAAAAAAAQABABAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBIgFgJQgKgVgCgWQgBAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgDgBIAAAAgACGhKQAAABgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIADAFQAMAZACAaQAAABAAAAQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgCgcgNgbIgDgGQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgCAAIgCAAgAh7hhQAAABgBAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgNATgJAWIgEAOQAAAAAAABQgBAAAAABQABAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAgBABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIAFgNQAHgWANgRQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgDgBIgBAAgAAziVQgBABAAAAQgBAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQABABAAAAQAAABAAAAQAAAAAAABQABAAAAABQAAAAABAAQAAABABAAQAbAKAUASQABAAAAAAQAAABABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAgBQAAAAAAAAQAAgBAAAAQABgBgBAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQgVgTgegLIgBAAIgCAAgAgGifQgeACgeANIAAABIgPAHQAAABgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAIAOgHIABgBQAbgNAcgBQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAIgEgCIAAAAg");
	this.shape_4.setTransform(33.4,33.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C4E0DE").s().p("Aj7D8QhphpAAiTQAAiSBphpQBphpCSAAQCTAABpBpQBpBpAACSQAACThpBpQhpBpiTAAQiSAAhphpg");
	this.shape_5.setTransform(33.4,33.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance_1}]},1).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.7,-0.5,68.3,67.8);


// stage content:



(lib.scene04_canvas_v03_trazado = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{transicion:2,inicio:1});

	// timeline functions:
	this.frame_0 = function() {
		//transicion de texto inicial
		
		this.stop();
	}
	this.frame_1 = function() {
		//etiqueta "inicio"
		
		this.stop();
		/* Evento MouseClick
		Al hacer clic en la instancia del símbolo especificado, se ejecuta una función a la que puede añadir su código personalizado.
		
		Instrucciones:
		1. Añada el código personalizado en una nueva línea después de la línea que dice "// Inicio del código personalizado" más abajo.
		El código se ejecutará al hacer clic en la instancia del símbolo.
		*/
		
        jQuery(document).on("final",function(){
            
            setTimeout(function(){
                
                this.gotoAndStop("transicion");
            
                
            }.bind(this),3000);
            
        }.bind(this));
        
		this.scene04_boton1.addEventListener("click", fl_MouseClickHandler_5.bind(this));
		
		function fl_MouseClickHandler_5()
		{
			// Inicio del código personalizado
			// Este código de ejemplo muestra las palabras "Ratón pulsado" en el panel Salida.
			jQuery(document).trigger("giraNino",[this]);
			// Fin del código personalizado
		}
	}
	this.frame_2 = function() {
		//transicion final
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1).call(this.frame_2).wait(1));

	// transicion
	this.transicion = new lib.transicion_nubes_on();
	this.transicion.setTransform(960,600,1,1,0,0,0,960,600);

	this.transicion_1 = new lib.transicion_nubes_off();
	this.transicion_1.setTransform(960,600,1,1,0,0,0,960,600);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.transicion}]}).to({state:[]},1).to({state:[{t:this.transicion_1}]},1).wait(1));

	// boton_marca
	this.scene04_boton1 = new lib.scene04_boton1();
	this.scene04_boton1.setTransform(960,273.1,0.76,0.76,0,0,0,33.4,33.4);
	new cjs.ButtonHelper(this.scene04_boton1, 0, 1, 2, false, new lib.scene04_boton1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.scene04_boton1).to({_off:true},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1137,52.5,4794.1,2445.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;